/* ================= RENDER ================= */
function spark(data,color='var(--brass)'){
  const w=320,h=64;if(data.length<2)return '<div class="empty-chart">График появится через пару месяцев</div>';
  const min=Math.min(0,...data),max=Math.max(1,...data),span=max-min||1,x=i=>i*(w/(data.length-1)),y=v=>h-3-(v-min)/span*(h-6);
  const pts=data.map((v,i)=>x(i).toFixed(1)+','+y(v).toFixed(1)).join(' ');
  const zero=min<0?`<line class="zero" x1="0" x2="${w}" y1="${y(0).toFixed(1)}" y2="${y(0).toFixed(1)}"/>`:'';
  return `<svg class="spark" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polygon points="0,${y(min)} ${pts} ${w},${y(min)}" fill="${color}" fill-opacity=".14"/>${zero}<polyline points="${pts}" fill="none" stroke="${color}" stroke-width="2" vector-effect="non-scaling-stroke"/></svg>`;
}
function qbar(r,label){const [l,tone]=qLabel(r);return `<div class="row small" style="margin-top:10px"><span class="muted">${esc(label||'Против соперников класса')}</span><span class="${tone}">${l} · <span class="num">${Math.round(r*100)}%</span></span></div><div class="bar qb" style="margin-top:6px"><i style="width:${Math.min(100,r/1.5*100)}%;background:var(--${tone})"></i><b></b></div>`;}
const pct=(x,d=0)=>(x*100).toFixed(d).replace('.',',')+'%';
function techEffects(lv){const e=[];if(lv.hrs)e.push(`−${Math.round((1-lv.hrs)*100)}% часов на машину`);if(lv.cap)e.push(`+${Math.round((lv.cap-1)*100)}% мощности`);if(lv.mat)e.push(`деталь дешевле на ${Math.round((1-lv.mat)*100)}%`);if(lv.def)e.push(`брак ${pct(lv.def,1)}`);if(lv.dem)e.push(`спрос +${Math.round(lv.dem*100)}%`);return e.join(' · ');}
function unitCost(md,s){s=s||G;return matCost(md,s)+hoursPerCar(md,s)/hoursPerWorker(s)*wageNow(s);}
function vPlant(){
  const s=G,L=s.last,cap=capEff(s),act=s.models.filter(m=>m.status==='prod');
  const util=L?Math.min(1,L.made/Math.max(1,cap)):0,hpw=hoursPerWorker(s);
  const avgH=act.length?act.reduce((a,m)=>a+hoursPerCar(m,s)*(m.lastMade||1),0)/Math.max(1,act.reduce((a,m)=>a+(m.lastMade||1),0)):0;
  const building=(s.capBuild||[]).reduce((a,b)=>a+b.units,0),cu=capUnitCost(s);
  const addQ=Math.max(2,Math.round(s.cap*0.25)),addH=Math.max(4,s.cap),ml=maxLoan(s),step=Math.max(1000,Math.round(ml/10/1000)*1000);
  const pl=L?`<table class="pl"><tr><td>Продажи (без скидки дилерам ${Math.round(dMargin(s)*100)}%)</td><td class="n">${money(L.rev)}</td></tr>${L.mil?`<tr><td>Военный заказ (${L.milX?`машин армии — ${fmtN(L.milN)}, военной продукции — ${fmtN(L.milX)} шт.`:`${fmtN(L.milN)} шт.`})</td><td class="n">${money(L.mil)}</td></tr>`:''}
    ${L.ord?`<tr><td>Заказы ведомств и фирм (${fmtN(L.ordN)} шт.)</td><td class="n">${money(L.ord)}</td></tr>`:''}${L.dump?`<tr><td>Распродажа излишков склада (${fmtN(L.dumpN)} шт.)</td><td class="n">${money(L.dump)}</td></tr>`:''}
    <tr><td>Детали и материалы</td><td class="n">−${money(L.mat)}</td></tr>${L.adm>1?`<tr><td>Контора: управление и сбыт</td><td class="n">−${money(L.adm)}</td></tr>`:''}<tr><td>Зарплата</td><td class="n">−${money(L.wage)}</td></tr><tr><td>Содержание завода</td><td class="n">−${money(L.ovh)}</td></tr>
    ${L.dlr?`<tr><td>Дилерская сеть</td><td class="n">−${money(L.dlr)}</td></tr>`:''}<tr><td>Реклама</td><td class="n">−${money(L.ad)}</td></tr>${L.rd?`<tr><td>Конструкторское бюро${L.rdp?`<br><span class="small muted">из них проекты: ${money(L.rdp)}</span>`:''}</td><td class="n">−${money(L.rd)}</td></tr>`:''}${L.drv?`<tr><td>Гонщики</td><td class="n">−${money(L.drv)}</td></tr>`:''}${L.team?`<tr><td>Гоночная команда</td><td class="n">−${money(L.team)}</td></tr>`:''}
    ${L.sto>1?`<tr><td>Склад</td><td class="n">−${money(L.sto)}</td></tr>`:''}${L.war>1?`<tr><td>Гарантийный ремонт</td><td class="n">−${money(L.war)}</td></tr>`:''}${L.fin?`<tr><td>Кредит покупателям: комиссия банкам<br><span class="small muted">в рассрочку куплено машин на ${money(L.finCr||0)}: деньги покупателям дают банки и финансовые дома — за это они берут около 6% суммы. Можно кредитовать покупателей самим — «Кредит покупателям» ниже.</span></td><td class="n">−${money(L.fin)}</td></tr>`:''}${L.finInc>1?`<tr><td>Своя кредитная компания: проценты с покупателей</td><td class="n good">+${money(L.finInc)}</td></tr>`:''}${L.finBad>1?`<tr><td>Невозвраты по рассрочке</td><td class="n">−${money(L.finBad)}</td></tr>`:''}${L.invInc>1?`<tr><td>Доход от вложений<br><span class="small muted">${[L.invB>1?'купоны облигаций '+money(L.invB):'',L.invD>1?'дивиденды по акциям '+money(L.invD):''].filter(Boolean).join(' · ')}</span></td><td class="n good">+${money(L.invInc)}</td></tr>`:''}${L.prm>1?`<tr><td>Спецакции: реклама и пробеги</td><td class="n">−${money(L.prm)}</td></tr>`:''}${L.promo>1?`<tr><td>Спецакции: скидки покупателям</td><td class="n">−${money(L.promo)}</td></tr>`:''}${L.tool?`<tr><td>Оснастка новых моделей</td><td class="n">−${money(L.tool)}</td></tr>`:''}${L.hire>1?`<tr><td>Найм и обучение</td><td class="n">−${money(L.hire)}</td></tr>`:''}${L.turn>1?`<tr><td>Текучесть: замена ушедших (${fmtN(s.quitN||0)} чел.)</td><td class="n">−${money(L.turn)}</td></tr>`:''}${L.fine?`<tr><td>Неустойка по заказам</td><td class="n">−${money(L.fine)}</td></tr>`:''}${L.legal?`<tr><td>Патенты и суды</td><td class="n">−${money(L.legal)}</td></tr>`:''}${L.licIn?`<tr><td>Отчисления вам за патенты</td><td class="n good">+${money(L.licIn)}</td></tr>`:''}
    ${L.tax-(L.wtax||0)>1?`<tr><td>Налог на прибыль${L.trate?` (${Math.round(L.trate*100)}%)`:''}</td><td class="n">−${money(L.tax-(L.wtax||0))}</td></tr>`:''}${L.invSh>1?`<tr><td>Доля партнёров и совладельцев${(s.partners||[]).length?` <span class="small muted">(слияния: ${(s.partners||[]).map(p=>esc(p.n)).join(', ')})</span>`:''}</td><td class="n">−${money(L.invSh)}</td></tr>`:''}${L.wtax>1||L.wtaxAcc>1?(()=>{const W=warTaxOf(s);return `<tr><td>Военный ${W?W.name.replace(/^военный /,''):'налог на сверхприбыль'}${L.wtaxBack>1?` <span class="small">(с долгом задним числом ${money(L.wtaxBack)})</span>`:''}<br><span class="small muted">${L.wtaxAcc>1&&!(L.wtax>1)?`Закон ещё не принят, но налог считают с начала войны — в этом месяце набежало ${money(L.wtaxAcc)}, всего ${money(s.wtaxDue||0)}. `:''}${W?esc(W.why):''}</span></td><td class="n">${L.wtax>1?'−'+money(L.wtax):'—'}</td></tr>`;})():''}${L.int?`<tr><td>Проценты по кредиту</td><td class="n">−${money(L.int)}</td></tr>`:''}<tr class="tot"><td>Итог за ${L.label}</td><td class="n ${L.profit>=0?'good':'bad'}">${money(L.profit)}</td></tr>
    ${L.got!==undefined?`<tr><td class="muted">Пришло денег от дилеров и ведомств</td><td class="n muted">${money(L.got)}</td></tr><tr><td class="muted">Ещё в пути (придут через 1–2 месяца)</td><td class="n muted">${money(arTotal(s))}</td></tr>`:''}${L.finOut>1||L.finIn>1?`<tr><td class="muted">Своя кредитная компания: выдано покупателям в рассрочку</td><td class="n muted">−${money(L.finOut||0)}</td></tr><tr><td class="muted">Вернули покупатели (без процентов)</td><td class="n muted">+${money(L.finIn||0)}</td></tr>`:''}${L.recall?`<tr><td class="bad">Банк списал в погашение кредита</td><td class="n bad">−${money(L.recall)}</td></tr>`:''}</table>
    <p class="small muted" style="margin-top:6px">Прибыль — не то же, что касса: дилеры платят за машины через месяц-два, а детали и зарплата оплачиваются сразу. Быстрый рост съедает деньги.</p>`
    :'<p class="small muted">Отчёт появится после первого месяца. Нажмите «Следующий месяц» внизу.</p>';
  // 0.22: в раскрытом виде — только то, что можно внедрить сейчас; внедрённое и будущее — в двух свёрнутых списках
  const techBld=k=>s.techBuild&&s.techBuild.k===k;
  const techNowRow=k=>{const d=TECH[k],l=techLv(s,k),nx=techNext(s,k),cost=techCost(s,k),bld=techBld(k),cat=!bld?techCatch(s,k):1;
    const status=bld?`<span class="pill warn">Внедряется · ${s.techBuild.left} мес.</span>`:`<button class="btn sm ${s.cash>=cost&&!s.techBuild?'primary':''}" data-act="tech" data-k="${k}" ${s.cash<cost||s.techBuild?'disabled':''}>${money(cost)}</button>`;
    return `<div class="tech-row"><div class="row"><div><h3>${d.name}${d.max>1?` <span class="muted small num">${l}/${d.max}</span>`:''}</h3><p class="small muted">${l?'Сейчас: '+d.lv[l-1].name:d.desc}</p></div>${status}</div>
      <p class="small" style="margin-top:4px">${bld?'Внедряем':'Дальше'}: <b>${nx.name}</b> — ${techEffects(nx)}${nx.hist?` <span class="muted">· в истории: ${nx.hist[1]}, ${nx.hist[0]}</span>`:''}</p>
      ${cat<1?`<p class="small good" style="margin-top:2px">Дешевле на ${Math.round((1-cat)*100)}%${techMonths(s,k)<3?' и на месяц быстрее':''}: другие заводы уже освоили — станки, мастера и советчики есть на рынке.</p>`:''}${!bld&&s.techBuild?'<p class="small muted" style="margin-top:2px">Начнёте, когда закончится текущее внедрение.</p>':!bld&&s.cash<cost?'<p class="small muted" style="margin-top:2px">Не хватает денег.</p>':''}</div>`;};
  const techDoneRow=k=>{const d=TECH[k],l=techLv(s,k);
    return `<div class="tech-row"><div class="row"><h3>${d.name}${d.max>1?` <span class="muted small num">${l}/${d.max}</span>`:''}</h3>${l>=d.max?'<span class="pill good">Всё внедрено</span>':''}</div>
      ${d.lv.slice(0,l).map(v=>`<p class="small" style="margin-top:3px">✓ <b>${v.name}</b> — ${techEffects(v)}</p>`).join('')}</div>`;};
  const techFutRow=k=>{const d=TECH[k],l=techLv(s,k),nx=techNext(s,k);const needT=nx.need?Object.keys(nx.need).filter(r=>techLv(s,r)<nx.need[r]).map(r=>TECH[r].name):[];
    return `<div class="tech-row off"><div class="row"><div><h3>${d.name}${d.max>1?` <span class="muted small num">${l}/${d.max}</span>`:''}</h3><p class="small muted">${d.desc}</p></div><span class="pill muted">${needT.length?'Нужно: '+needT.join(', '):'С '+(nx.y-techEarly(s))+' г.'}</span></div>
      ${d.lv.slice(l).map((v,j)=>`<p class="small" style="margin-top:3px">${j?'· потом':'Дальше'}: <b>${v.name}</b> — ${techEffects(v)}${v.y?` <span class="muted">· ${v.y-techEarly(s)} г.</span>`:''}</p>`).join('')}</div>`;};
  const tNow=TECH_ORDER.filter(k=>techNext(s,k)&&(techOpen(s,k)||techBld(k))),tDone=TECH_ORDER.filter(k=>techLv(s,k)>0),tFut=TECH_ORDER.filter(k=>techNext(s,k)&&!techOpen(s,k)&&!techBld(k));
  const techLvSum=TECH_ORDER.reduce((a,k)=>a+techLv(s,k),0),techMaxSum=TECH_ORDER.reduce((a,k)=>a+TECH[k].max,0);
  const techs=`${tNow.length?`<div class="label" style="margin-top:10px">Можно внедрить сейчас</div>${tNow.map(techNowRow).join('')}`:'<p class="small muted" style="margin-top:8px">Сейчас внедрять нечего: новые технологии откроются с годами и после внедрения других.</p>'}
    <div style="margin-top:10px">${fold('techDone','Внедрённые технологии',tDone.length?tDone.map(techDoneRow).join(''):'<p class="small muted">Пока ничего: завод работает по старинке.</p>',false,`${techLvSum} из ${techMaxSum} ступеней`)}</div>
    <div style="margin-top:6px">${fold('techFut','Будущие технологии',tFut.length?tFut.map(techFutRow).join(''):'<p class="small muted">Всё доступное уже открыто.</p>',false,`${tFut.length} ${plural(tFut.length,'направление','направления','направлений')} · откроются позже`)}</div>`;
  const P=PIONEERS[s.pioneer],wp=s.wagePol||'market';
  const staffHTML=`    <div class="chips" style="margin-top:8px"><button class="chip ${s.staffAuto?'on':''}" data-act="staffAuto" data-v="1">Нанимать по плану выпуска<small>отдел кадров сам держит нужный штат</small></button><button class="chip ${s.staffAuto?'':'on'}" data-act="staffAuto" data-v="0">Вручную<small>шаг — 10% штата</small></button></div>
    <div class="label" style="margin-top:12px">Зарплата</div><div class="chips">${Object.entries(WAGE_POL).map(([k,w])=>`<button class="chip ${wp===k?'on':''}" data-act="wagePol" data-v="${k}" ${w.y&&s.y<w.y-techEarly(s)?'disabled':''}>${w.name}<small>×${String(w.k).replace('.',',')} ставки · выработка ${w.prod>=1?'+':'−'}${Math.round(Math.abs(w.prod-1)*100)}% · текучесть ${w.turn}${w.y&&s.y<w.y-techEarly(s)?' · с '+(w.y-techEarly(s))+' г.':''}</small></button>`).join('')}</div>`;
  return `<div class="scene">${plantHTML(s)}</div>
  ${advisorCard(s)}
  <div class="kpis"><div class="kpi"><span class="label">Прибыль</span><b class="${L&&L.profit<0?'bad':''}">${L?money(L.profit):'—'}</b></div><div class="kpi"><span class="label">Продано</span><b>${L?fmtN(L.sold+(L.milN||0)+(L.ordN||0))+' шт.':'—'}</b>${L&&(L.milN||L.ordN)?`<small class="muted" style="display:block;font-size:11px;margin-top:2px">${[L.sold?'покупателям '+fmtN(L.sold):'',L.milN?'армии '+fmtN(L.milN):'',L.ordN?'по заказам '+fmtN(L.ordN):''].filter(Boolean).join(' · ')}</small>`:''}</div><div class="kpi"><span class="label">Репутация</span><b>${Math.round(s.rep)}<span class="muted small">/100</span></b></div></div>
  ${s.pioneer!=='custom'?`<section class="card" style="display:grid;grid-template-columns:64px 1fr;gap:12px;align-items:center"><button class="pion-link" data-act="founder" style="width:64px" aria-label="Об основателе">${portraitHTML(s.pioneer)}</button><div><h3>${P.name} <button class="btn sm" data-act="founder">О нём ▸</button></h3><div class="bon">${P.plus.map(x=>`<span class="p">${x}</span>`).join('')}${P.minus.map(x=>`<span class="m">${x}</span>`).join('')}</div></div></section>`:''}
  <section class="card"><div class="row"><span class="label">Касса по месяцам</span><span class="small muted num">${money(s.cash)}</span></div>${spark(s.hist.cash)}</section>
  ${foldCard('cap',true,'<h2>Мощности</h2>',`
    <div class="row" style="margin-top:8px"><div><h3><span class="num">${fmtN(Math.round(cap))}</span> машин в месяц</h3><p class="small muted">${s.shifts>1?'Две смены':'Одна смена'} · простая машина в пересчёте${building?` · строится ещё ${fmtN(Math.round(building*techMul(s,'cap')*(s.shifts>1?1.85:1)))}`:''}</p></div><span class="num ${util>0.95?'warn':''}">${Math.round(util*100)}%</span></div>
    <div class="bar" style="margin-top:6px"><i style="width:${util*100}%;background:var(--brass)"></i></div>
    <p class="small muted" style="margin-top:4px">Загрузка в прошлом месяце. Сложные модели занимают больше места на линии.</p>
    <div class="btns" style="margin-top:10px"><button class="btn" data-act="capAdd" data-n="${addQ}" ${s.cash<addQ*cu?'disabled':''}>+25% · ${money(addQ*cu)}</button><button class="btn" data-act="capAdd" data-n="${addH}" ${s.cash<addH*cu?'disabled':''}>Удвоить · ${money(addH*cu)}</button>${s.cap>3?`<button class="btn sm" data-act="capSell">Продать 20%</button>`:''}</div>
    <p class="small muted" style="margin-top:6px">Цех строится ${capMonths(s,addQ)}–${capMonths(s,addH)} месяцев: стройте заранее, пока спрос растёт. Место под одну машину в месяц стоит ${money(cu)}; содержание — около 1% стоимости завода в месяц.${(s.capBuild||[]).length?' Идёт стройка: '+s.capBuild.map(b=>`+${fmtN(b.units)} мест — ещё ${b.left} мес.`).join(', ')+'.':''}${convRebuild(s)?' <b class="warn">Цех перестраивают под конвейер: выпуск ниже на четверть.</b>':''}</p>
    <div class="label" style="margin-top:12px">Смены</div><div class="chips"><button class="chip ${s.shifts>1?'':'on'}" data-act="shifts" data-v="1">Одна<small>обычная ставка</small></button><button class="chip ${s.shifts>1?'on':''}" data-act="shifts" data-v="2">Две<small>мощность ×1,85, зарплата +8%, содержание +10%</small></button></div>`,`${fmtN(Math.round(cap))} машин в месяц · загрузка ${Math.round(util*100)}%${building?' · строится':''}`)}
  ${foldCard('staffc',true,'<h2>Рабочие</h2>',`
    <div class="row" style="margin-top:8px"><div><h3><span class="num">${fmtN(s.workers)}</span> рабочих</h3><p class="small muted">${money(wageNow(s))} в месяц на человека · ${Math.round(hpw)} ч в месяц</p></div>${s.staffAuto?'<span class="pill good">Штат по плану</span>':`<div class="step"><button data-act="workers" data-d="-1" aria-label="Сократить">−</button><span>${fmtN(s.workers)}</span><button data-act="workers" data-d="1" aria-label="Нанять">+</button></div>`}</div>
    <div class="row small" style="margin-top:8px"><span class="muted">На одну машину уходит</span><span class="num">${fmtN(Math.round(avgH))} человеко-часов</span></div>
    ${DIF().simple&&helperOn(s)?'<p class="small muted" style="margin-top:6px">Людей нанимает отдел кадров по плану выпуска.</p>':fold('staff','Найм и зарплата',staffHTML,false,(s.staffAuto?'штат по плану · ':'вручную · ')+WAGE_POL[wp].name.toLowerCase())}
  `,`${fmtN(s.workers)} рабочих · ${money(wageNow(s))} в месяц`)}
  ${whCard(s)}
  ${foldCard('techc',false,'<h2>Технологии завода</h2>',`<p class="small muted" style="margin-top:2px">Внедряется одна технология за раз, 3 месяца. Сильное КБ открывает их раньше истории — это «первенства» в зачёт наследия.</p>
    ${techs}`,`внедрено ${techLvSum} из ${techMaxSum}${s.techBuild?' · внедряется: '+esc(techNext(s,s.techBuild.k).name):tNow.length?' · можно начать: '+tNow.length:''}`)}
  ${foldCard('fin',true,'<h2>Финансы</h2>',`${L?`<div class="row small" style="margin-top:8px"><span class="muted">Итог за ${L.label}</span><b class="num ${L.profit>=0?'good':'bad'}">${money(L.profit)}</b></div>`:''}${fold('pl','Доходы и расходы по статьям',pl,false)}<div class="hr"></div>
    <div class="row"><div><h3>Кредит: <span class="num">${money(s.loan)}</span></h3><p class="small muted">${pct(loanRate(s),1)} годовых · лимит ${money(ml)} (залог — завод и склад)</p>${creditState(s).t?`<p class="small ${creditState(s).closed?'bad':'warn'}">${esc(creditState(s).t)}</p>`:''}</div><div class="btns"><button class="btn" data-act="loan" data-n="${step}" ${s.loan+step>ml||!loanOpen(s)?'disabled':''}>+${fmtN(step)}</button>${(()=>{const can=Math.min(s.loan,Math.floor(Math.max(0,s.cash)));return `<button class="btn" data-act="repay" ${s.loan<1||can<Math.min(100,s.loan)?'disabled':''}>${s.loan>=1&&can>=s.loan?'Погасить всё':s.loan>=1&&can>=100?'Погасить '+moneyC(can):'Погасить'}</button>`;})()}</div></div>
    ${finCreditHTML(s)}${invHTML(s)}
    <div class="row small" style="margin-top:8px"><span class="muted">Стоимость компании</span><span class="num">${money(companyValue(s))}</span></div>`,L?`итог за ${L.label}: ${money(L.profit)} · кредит ${money(s.loan)}`:'')}`;
}
function whCard(s){const st=whStock(s),cap=whCap(s),f=st/Math.max(1,cap),uc=whUnitCost(s),a=Math.max(5,Math.round(cap*0.5)),b=Math.max(10,cap),bld=(s.whBuild||[]).reduce((x,y)=>x+y.units,0),L=s.last;
  return foldCard('wh',true,'<h2>Склад</h2>',`<div class="row" style="margin-top:8px"><div><h3><span class="num">${fmtN(st)}</span> из ${fmtN(cap)} мест</h3><p class="small muted">Место под одну машину — ${money(uc)}${bld?` · строится ещё ${fmtN(bld)}`:''}</p></div><span class="num ${f>0.9?'warn':''}">${Math.round(f*100)}%</span></div>
    <div class="bar" style="margin-top:6px"><i style="width:${Math.min(100,f*100)}%;background:var(--${f>0.9?'warn':'brass'})"></i></div>
    ${L&&L.dumpN?`<p class="small bad" style="margin-top:6px">Не поместились ${fmtN(L.dumpN)} машин — ушли перекупщикам за полцены.</p>`:''}
    <div class="btns" style="margin-top:10px"><button class="btn" data-act="whAdd" data-n="${a}" ${s.cash<a*uc?'disabled':''}>+${fmtN(a)} мест · ${money(a*uc)}</button><button class="btn" data-act="whAdd" data-n="${b}" ${s.cash<b*uc?'disabled':''}>Удвоить · ${money(b*uc)}</button></div>
    <p class="small muted" style="margin-top:6px">Склад строится ${whMonths(s)} мес. Хранение — 1% стоимости машин в месяц. Запас машин спасает, когда спрос выше прогноза, а всё, что не влезло, забирают перекупщики за полцены.</p>`,`${fmtN(st)} из ${fmtN(cap)} мест · ${Math.round(f*100)}%`);}
// Сколько завод выпустит в этом месяце при плане «авто»
function autoPlan(md){return Math.max(0,Math.round((md.fc||0)*1.04+(md.backlog||0)-((md.stock||0)-0.35*(md.fc||0))));}
const fmtD=x=>x>0&&x<10?(Math.round(x*10)/10).toString().replace('.',','):fmtN(x);
function planStep(md,sm){const auto=md.plan==='auto'||md.plan===undefined,n=auto?autoPlan(md):+md.plan,st=Math.max(1,Math.round(Math.max(n,md.fc||1)*0.1));
  return `<div class="step${sm?' sm':''}"><button data-act="plan" data-id="${md.id}" data-d="${-st}" aria-label="Выпускать меньше">−</button><span>${fmtN(n)}</span><button data-act="plan" data-id="${md.id}" data-d="${st}" aria-label="Выпускать больше">+</button></div>`;}
// Себестоимость и экономия масштаба: из чего она складывается и сколько стоила бы машина при большем выпуске
function costHTML(md,s){if(md.status!=='prod')return '';const v=Math.max(1,modelVol(md)),mat=matCost(md,s),lab=hoursPerCar(md,s)/hoursPerWorker(s)*wageNow(s),at=k=>unitCost({...md,vol:v*k},s),l=1-labLearn(md);
  return `<p class="small muted" style="margin-top:6px">Себестоимость ${money(mat+lab)} = детали ${money(mat)} + работа ${money(lab)} при выпуске ≈ ${fmtD(v)} в месяц. <span class="good">Больше выпуск — дешевле машина:</span> при ${fmtN(v*3)} в месяц — ${money(at(3))}, при ${fmtN(v*10)} — ${money(at(10))}${l>0.02?`. Опыт рабочих: ${fmtN(md.made||0)} машин уже собрано — работы на ${Math.round(l*100)}% меньше`:''}.</p>`;}
// 0.26: грузовик — для каких перевозок он годится: цена тонно-километра против эталона соперников и кто его взял
function cpkTxt(x){if(!isFinite(x)||x<=0)return '—';if(x<0.1)return (Math.round(x*1000)/10).toString().replace('.',',')+'¢';if(x<1)return Math.round(x*100)+'¢';return '$'+x.toFixed(2).replace('.',',');}
function truckHint(md,s){if(!isTruck(md)||md.status==='off')return '';const c=s.country,PT=prefP('truck',c,s),U=md.useD||{},tot=TUSE.reduce((a,u)=>a+(U[u]||0),0),sh=truckUseSh(c,s);
  const rows=TUSE.filter(u=>sh[u]>0.005).map(u=>{const ref=truckRef(u,s.y),cR=truckCost(ref,u,c,s,PT*payK(ref)).cpk,cM=truckCost(md,u,c,s,md.price).cpk,r=cR/cM,tone=r>=1.05?'good':r<0.9?'bad':'muted';
    return `<tr><td>${TRUCK_USE[u].n}<small class="muted"> · ${esc(TRUCK_USE[u].who)}</small></td><td class="n ${tone}">${cpkTxt(cM)}</td><td class="n muted">${cpkTxt(cR)}</td><td class="n">${md.status==='prod'&&tot>0?pct((U[u]||0)/tot,0):'—'}</td></tr>`;}).join('');
  return `<div class="label" style="margin-top:10px">Тонно-километр: во что обходится перевозка</div><table class="pl ptab ctab" style="margin-top:4px"><tr><th>Перевозки</th><th class="n">Ваша</th><th class="n">Соперники</th><th class="n">Берут</th></tr>${rows}</table>
    <p class="small muted" style="margin-top:4px">Фирма считает всё: машину за годы службы, ремонт и простои, бензин, шофёра — и сколько тонн машина перевезёт за день. Фургон хорош для развозки по району, полуторатонка — по городу, трёхтонка — между городами: одна машина другую не заменяет. «Берут» — кто купил вашу машину в прошлом месяце.</p>`;}
function stockWarn(md){return md.status==='prod'&&md.stock>Math.max(3,(md.fc||0)*3);}
// Сворачиваемые разделы: длинные списки открываются, когда нужны
const UIF={};
// что свёрнуто — запоминается в сохранении
function isOpen(k,def){const f=G&&G.ui&&G.ui.f,v=f&&f[k]!==undefined?f[k]:UIF[k];return v===undefined?!!def:v;}
function setOpen(k,v){UIF[k]=v;if(G){G.ui=G.ui||{};G.ui.f=G.ui.f||{};G.ui.f[k]=v;}}
// Карточка, которую можно свернуть: заголовок — кнопка; свёрнутая показывает одну строку итога
function foldCard(k,def,head,body,sum,cls){const o=isOpen(k,def);return `<section class="card${cls?' '+cls:''}${o?'':' folded'}"><button class="card-h" data-act="fold" data-k="${k}" data-def="${def?1:0}" aria-expanded="${o}"><span class="ch">${head}</span><i>${o?'▴':'▾'}</i></button>${o?body:(sum?`<p class="small muted card-sum">${sum}</p>`:'')}</section>`;}
function fold(k,title,inner,def,sub){const o=isOpen(k,def);return `<button class="fold-h" data-act="fold" data-k="${k}" data-def="${def?1:0}"><span>${title}${sub?`<small>${sub}</small>`:''}</span><i>${o?'▴':'▾'}</i></button>${o?`<div class="fold-b">${inner}</div>`:''}`;}
// Почему продали меньше, чем хотели купить
function lostLine(md){if(md.status!=='prod'||md.lastWant===undefined)return '';const w=md.lastWant||0,sold=md.lastSold||0;if(w<0.5)return '<p class="small muted" style="margin-top:6px">В прошлом месяце покупателей не нашлось: проверьте цену, дилеров и сравнение с соперником.</p>';
  if(w-sold<0.6)return `<p class="small good" style="margin-top:6px">Продано всё, что хотели купить${sold?` — ${fmtN(sold)} шт.`:'.'}</p>`;
  const L=[];if((md.lostS||0)>=0.5)L.push(`не хватило машин — ${fmtD(md.lostS)}${(md.queued||0)>=1?` (${fmtN(md.queued)} ждут в очереди)`:''}`);if((md.lostD||0)>=0.5)L.push(`дилеры не успели — ${fmtD(md.lostD)}`);
  return `<p class="small warn" style="margin-top:6px">Хотели купить ≈ ${fmtD(w)}, продано ${fmtN(sold)}${L.length?': '+L.join(', '):''}. ${(md.lostS||0)>=(md.lostD||0)?'Выпускайте больше или расширьте склад.':'Откройте дилеров на вкладке «Рынок».'}</p>`;}
function planCard(s){const act=s.models.filter(m=>m.status==='prod');if(!act.length)return '';
  const rows=act.map(md=>{const auto=md.plan==='auto'||md.plan===undefined,w=stockWarn(md),TT=techTone(md,s);
    return `<div class="plan-row"><div class="row ctl"><div><h3><span class="${TT.tone}" title="Против соперников класса">${esc(md.name)}</span> <small class="num ${TT.tone}">${Math.round(TT.r*100)}%</small> <span class="pill ${auto?'good':'warn'}">${auto?'авто':'вручную'}</span></h3>
      <p class="small muted">выпуск ${fmtN(md.lastMade||0)} · продано ${fmtN(md.lastSold||0)}${md.ordSold?` · по заказам ${fmtN(md.ordSold)}`:''} · склад <b class="${w?'warn':''}">${fmtN(md.stock)}</b>${md.backlog>1?` · очередь ${fmtN(md.backlog)}`:''}</p></div>${auto&&!isOpen('plan'+md.id)?`<button class="btn sm" data-act="fold" data-k="plan${md.id}">Вручную ▾</button>`:planStep(md,1)}</div>
      ${w?`<p class="small warn" style="margin-top:4px">Машины копятся на складе и дешевеют: снизьте выпуск или цену.</p>`:''}
      ${auto?(isOpen('plan'+md.id)?`<p class="small muted" style="margin-top:4px">Нажмите − или +, чтобы выпускать своё число машин вместо «авто».</p>`:''):`<button class="btn sm" style="margin-top:6px" data-act="planAuto" data-id="${md.id}">Вернуть «авто»</button>`}</div>`;}).join('');
  const wf=whStock(s)/Math.max(1,whCap(s)),made=act.reduce((a,m)=>a+(m.lastMade||0),0),sold=act.reduce((a,m)=>a+(m.lastSold||0),0);
  return foldCard('planlist',act.length<=3,`<h2>Выпуск</h2><span class="label">${act.length} ${plural(act.length,'модель','модели','моделей')} · машин в месяц</span>`,`${rows}
    <div class="row small" style="margin-top:8px"><span class="muted">Склад: ${fmtN(whStock(s))} из ${fmtN(whCap(s))} мест</span><span class="num ${wf>0.9?'warn':''}">${Math.round(wf*100)}%</span></div><div class="bar" style="margin-top:4px"><i style="width:${Math.min(100,wf*100)}%;background:var(--${wf>0.9?'warn':'brass'})"></i></div>
    <p class="small muted" style="margin-top:8px">Цвет названия — какая машина против соперников класса: <span class="good">зелёная — лучше</span>, <span class="warn">жёлтая — наравне</span>, <span class="bad">красная — хуже</span>. «Авто» — завод делает столько, сколько берут покупатели, и не больше, чем поместится на складе.</p>`,
    `выпуск ${fmtN(made)} · продано ${fmtN(sold)} · склад ${Math.round(wf*100)}% · ${act.map(md=>{const TT=techTone(md,s);return `<span class="${TT.tone}">${esc(md.name)}</span>`;}).join(', ')}`);}
function ordersCard(s){const L=s.orders||[];if(!L.length)return '';
  const late=L.filter(o=>o.due-mi(s)<=1&&o.left>0).length;
  return foldCard('orders',false,`<h2>Заказы</h2><span class="pill ${late?'warn':'good'}">${L.length}</span>`,`${L.map(o=>{const md=s.models.find(m=>m.id===o.md),done=o.n-o.left,left=o.due-mi(s);
    return `<div class="plan-row"><div class="row"><div><h3>${esc(o.who)}</h3><p class="small muted">«${esc(md?md.name:'?')}» · ${money(o.price)} за машину · осталось ${left} мес.</p></div><span class="num">${fmtN(done)}/${fmtN(o.n)}</span></div><div class="bar" style="margin-top:6px"><i style="width:${done/o.n*100}%;background:var(--good)"></i></div></div>`;}).join('')}
    <p class="small muted" style="margin-top:8px">Заказы выполняются сами: машины для них завод делает сверх плана и отдаёт в первую очередь. Не успеете к сроку — неустойка и удар по репутации.</p>`,
    L.map(o=>{const md=s.models.find(m=>m.id===o.md);return `${esc(o.who)}: ${fmtN(o.n-o.left)}/${fmtN(o.n)}${md?' «'+esc(md.name)+'»':''}`;}).join(' · ')+(late?' · <span class="warn">срок на исходе</span>':''));}
function rdCardHTML(s){const rd=s.rd,L=rdActive(s),tot=rdTotal(s),slots=rdSlots(s),free=slots-L.length;
  const rows=L.map((pj,i)=>{const pts=rdPtsOf(s,pj);return `<div class="rd-row"><div class="row small"><span>${pj.kind==='upg'?'Улучшение':pj.kind==='study'?'Изучение машины конкурента':'Прототип'}: <b>${esc(pj.name)}</b>${pj.kind==='upg'?' ★'+pj.lvl:''}</span><button class="iconbtn sm" data-act="rdStop" data-k="${i}" aria-label="Остановить проект">×</button></div>
    <div class="bar" style="margin-top:6px"><i style="width:${Math.max(2,Math.min(100,(pj.prog||0)/pj.need*100))}%;background:var(--brass)"></i></div>
    <div class="row small muted" style="margin-top:4px"><span>${Math.floor(pj.prog||0)} из ${pj.need} · готово через ~${Math.max(1,Math.ceil((pj.need-(pj.prog||0))/pts))} мес.</span>${L.length>1?`<div class="step sm"><button data-act="rdW" data-k="${i}" data-d="-1" aria-label="Меньше сил">−</button><span>${Math.round(rdShare(s,pj)*100)}%</span><button data-act="rdW" data-k="${i}" data-d="1" aria-label="Больше сил">+</button></div>`:'<span>все силы бюро</span>'}</div></div>`;}).join('');
  return `<section class="card"><div class="row"><h2>Конструкторское бюро</h2><span class="pill warn">${rd.lvl}/${RD_MAX}</span></div>
    <p class="small muted" style="margin-top:4px">${RD_LV[rd.lvl]} · инженеров ${rd.lvl*4} · ${money(rdUpkeep(s))} в месяц · ${tot.toFixed(1).replace('.0','').replace('.',',')} очк. в месяц на всё бюро. Один проект получает все силы; если ведёте несколько, распределите силы кнопками − и +. Одновременно — до ${slots} проектов.</p>
    ${rows}${!L.length?'<p class="small warn" style="margin-top:10px">Бюро простаивает — выберите проект.</p>':''}
    <div class="btns" style="margin-top:10px">${free>0?`<button class="btn ${L.length?'':'primary'}" data-act="rdPick">+ Проект</button>`:''}<button class="btn" data-act="rdUp" ${rd.lvl>=RD_MAX||s.cash<rdUpCost(s)?'disabled':''}>${rd.lvl>=RD_MAX?'Высший уровень':'Расширить · '+money(rdUpCost(s))}</button></div>
    ${rd.lvl<RD_MAX?`<p class="small muted" style="margin-top:6px">Уровень ${rd.lvl+1} — «${RD_LV[rd.lvl+1]}»: больше инженеров${rdSlots({rd:{lvl:rd.lvl+1}})>slots?', ещё один проект одновременно':''}${rd.lvl+1>=5&&rd.lvl<5?', улучшения до ★4':rd.lvl+1>=7&&rd.lvl<7?', улучшения до ★5':''}, прототипы дальше в будущее.</p>`:''}</section>`;}
function specLine(md,s){const p=parts(md),st=x=>upgL(x.id)?' ★'+upgL(x.id):'';return PART_KEYS.map(k=>p[k].name+st(p[k])).join(' · ')+' · '+trimName(p.t,s);}
// Во сколько раз машина лучше соперников класса — цветом: зелёная лучше, жёлтая наравне, красная хуже
function techTone(md,s){const r=classScore(md,s);return {r,tone:r>=1.08?'good':r>=0.9?'warn':'bad'};}
// Что будет при другой цене: спрос, выпуск, себестоимость при этом выпуске (экономия масштаба) и прибыль
// Прогноз при текущей цене и сдвиг против цены в начале месяца — видно сразу, как нажали − или +
// Прогноз цены — по всей марке, как в ходе месяца: дешевле эта модель — часть покупателей уходит к ней с ваших же моделей;
// продать можно не больше, чем успеют дилеры в каждой стране и завод (мощность делится между моделями по спросу)
function brandFc(md,s,p){const r=demandAll(s,{id:md.id,price:p}),cr=techLv(s,'credit')?1.15:1,act=s.models.filter(m=>m.status==='prod'||m.status==='sale');
  const want={};act.forEach(m=>{for(const c in r.by[m.id])want[c]=(want[c]||0)+r.by[m.id][c]*cr;});
  const fcC={};for(const c in want){const cap=dealerCapOf(s,c);fcC[c]=want[c]>cap&&want[c]>0?cap/want[c]:1;}
  const wantM=act.map(m=>{let d=0;for(const c in r.by[m.id])d+=r.by[m.id][c]*cr;return d;}),dem=act.map(m=>{let d=0;for(const c in r.by[m.id])d+=r.by[m.id][c]*cr*fcC[c];return d;});
  const cx=act.map(complexity),cap=capEff(s),need=dem.reduce((a,d,i)=>a+(act[i].status==='sale'?0:d*cx[i]),0),kC=need>0?Math.min(1,cap/need):1;
  let tot=0,self=null,oth=0;act.forEach((m,i)=>{const pp=m.id===md.id?p:m.price,sold=m.status==='sale'?Math.min(dem[i],m.stock):dem[i]*kC+Math.min(Math.max(0,m.stock)/4,dem[i]*(1-kC));
    const uc=unitCost({...m,vol:Math.max(1,sold)},s),mg=pp*(1-dMargin(s))-uc,pr=sold*mg;tot+=pr;if(m.id===md.id)self={d:sold,want:wantM[i],uc,m:mg,pr};else oth+=sold;});
  return Object.assign(self||{d:0,want:0,uc:0,m:0,pr:0},{brand:tot,oth,lim:kC<0.98?'plant':Object.values(fcC).some(k=>k<0.98)?'dealers':''});}
function priceFc(md,s,p){return brandFc(md,s,p);}
function priceLine(md,s){if(md.status!=='prod')return '';const a=priceFc(md,s,md.price),b=md.pPrev&&md.pPrev!==md.price&&md.pPrevM===mi(s)?priceFc(md,s,md.pPrev):null;
  const dl=(x,y)=>{if(!b||Math.abs(y)<1e-6)return '';const r=(x-y)/Math.abs(y);if(Math.abs(r)<0.005)return '';return ` <small class="${r>0?'good':'bad'}">${r>0?'▲':'▼'}${Math.round(Math.abs(r)*100)}%</small>`;};
  const many=s.models.filter(m=>m.status==='prod'||m.status==='sale').length>1,dO=b&&many?a.oth-b.oth:0;
  return `<div class="pfc"><div>Продажи в мес.<b>${fmtD(a.d)}${dl(a.d,b&&b.d)}</b></div><div>Маржа<b class="${a.m<0?'bad':''}">${money(a.m)}${dl(a.m,b&&b.m)}</b></div><div>${many?'Прибыль марки':'Прибыль в мес.'}<b class="${a.brand<0?'bad':''}">${money(a.brand)}${dl(a.brand,b&&b.brand)}</b></div></div>
    ${a.lim&&a.want>a.d*1.02+0.3?`<p class="small warn" style="margin-top:2px">Хотят купить ${fmtD(a.want)} в мес., но ${a.lim==='plant'?'завод не успеет выпустить больше':'дилеры не успеют продать больше'} — прогноз считает только то, что правда продастся.</p>`:''}
    ${b?`<p class="small muted" style="margin-top:2px">Сравнение — с ценой в начале месяца (${money(md.pPrev)}).${Math.abs(dO)>=1?` Другие ваши модели: ${dO<0?'−':'+'}${fmtD(Math.abs(dO))} машин в мес. — ${dO<0?'часть покупателей ушла к этой модели':'часть покупателей вернулась к ним'}.`:''}</p>`:''}`;}
function priceTable(md,s){const P=md.price,many=s.models.filter(m=>m.status==='prod'||m.status==='sale').length>1,rows=[[0.9,'−10%'],[1,'сейчас'],[1.1,'+10%']].map(([k,lab])=>{const p=Math.round(P*k/10)*10,f=brandFc(md,s,p);return {p,lab,d:f.d,uc:f.uc,pr:f.brand,oth:f.oth,now:k===1};});
  const best=rows.reduce((a,b)=>b.pr>a.pr?b:a,rows[0]),o0=rows[1].oth;
  return `<table class="pl ptab" style="margin-top:8px"><tr><th>Цена</th><th class="n">Продажи</th><th class="n">Себест.</th><th class="n">${many?'Прибыль марки':'Прибыль'}</th></tr>${rows.map(r=>`<tr class="${r.now?'you':''}"><td>${money(r.p)} <small>${r.lab}</small></td><td class="n">${fmtD(r.d)}${many&&!r.now&&Math.abs(r.oth-o0)>=1?`<small class="muted">другие ${r.oth<o0?'−':'+'}${fmtD(Math.abs(r.oth-o0))}</small>`:''}</td><td class="n">${money(r.uc)}</td><td class="n ${r.pr<0?'bad':r===best?'good':''}">${money(r.pr)}</td></tr>`).join('')}</table>
    <p class="small muted" style="margin-top:4px">В месяц. ${many?'Прибыль — всей марки: подешевела эта модель — часть покупателей уходит к ней с других ваших моделей («другие −…»). ':''}Продажи — не больше, чем успеют завод и дилеры. Себестоимость — при таком выпуске: больше продаёте — дешевле каждая машина.</p>${dutyLines(md,s)}`;}
// 0.21: за границей к цене добавляются пошлина и доставка; 0.26: своя цена в каждой стране и маржа с машины
function dutyLines(md,s){const L=Object.keys(COUNTRIES).filter(c=>c!==s.country&&dealerCount(s,c)>0);if(!L.length)return '';const uc=unitCost(md,s);
  const rows=[s.country,...L].map(c=>{if(c!==s.country&&tradeBan(s,c))return `<tr><td>${COUNTRIES[c].name}</td><td class="n bad" colspan="3">ввоз запрещён</td></tr>`;
    const buyer=offerPrice(md,c,s),net=netPer(md,c,s),m=licOn(s,c)?net:net-uc,k=pmkOf(s,c),tf=tariffOf(md,c,s),sh=shipCostTo(s,c)*shipK(s,c),IL=c===s.country?null:impOf(s,c);
    const why=[c===s.country?'дома':'',k!==1?`цена ${k>1?'+':'−'}${Math.round(Math.abs(k-1)*100)}%`:'',tf>0?`пошлина ${pct(tf,0)}`:'',sh>0?`доставка ${money(sh)}`:'',IL&&IL.cut?`импортёру ${pct(IL.cut,0)}`:'',licOn(s,c)?'лицензия':''].filter(Boolean).join(', ');
    return `<tr><td>${COUNTRIES[c].name}${why?`<small class="muted">${why}</small>`:''}</td><td class="n">${money(buyer)}</td><td class="n">${money(net)}</td><td class="n ${m<0?'bad':'good'}">${money(m)}</td></tr>`;}).join('');
  return `<div class="label" style="margin-top:10px">По странам: цена и маржа с машины</div><table class="pl ptab ctab" style="margin-top:4px"><tr><th>Страна</th><th class="n">Покупатель</th><th class="n">Вам</th><th class="n">Маржа</th></tr>${rows}</table>
    <p class="small muted" style="margin-top:4px">«Вам» — после скидки дилеру${L.some(c=>impOf(s,c)&&impOf(s,c).cut)?' и импортёру':''} и доставки; маржа — минус себестоимость.${L.some(c=>licOn(s,c))?` По лицензии вам — ${Math.round(LIC_ROY*100)}% цены с каждой машины: её делает и продаёт местный завод.`:''} Цену для каждой страны можно поднять или снизить на вкладке «Рынок».</p>`;}
function vModels(){
  const s=G,ord={prod:0,sale:1,dev:2,off:3},many=s.models.filter(m=>m.status!=='off').length>1;
  const card=md=>{
    const g=segOf(md),uc=unitCost(md,s),ref=refPrice(md,s),net=md.price*(1-dMargin(s)),C=classCompare(md,s,s.country),TT=techTone(md,s);
    const pill=md.status==='sale'?`<span class="pill warn">Распродажа · ${fmtN(md.stock)} шт.</span>`:md.status==='prod'?'<span class="pill good">В продаже</span>':md.status==='dev'?`<span class="pill warn">Разработка · ${md.devLeft} мес.</span>`:'<span class="pill muted">Снята</span>';
    const margin=net-uc,enter=md.fresh?' enter':'';md.fresh=0;const key='md'+md.id,open=isOpen(key,!many||md.status==='dev');
    let el='';if(md.status==='prod'&&open)el=priceTable(md,s);
    const ctl=md.status!=='off'&&md.status!=='dev'?`<div class="row ctl" style="margin-top:10px"><div><span class="label">Цена</span><p class="small muted">типичная для такой машины ≈ <span class="num">${money(ref)}</span></p></div><div class="step"><button data-act="price" data-id="${md.id}" data-d="-1" aria-label="Снизить цену">−</button><span>${money(md.price)}</span><button data-act="price" data-id="${md.id}" data-d="1" aria-label="Поднять цену">+</button></div></div>${priceLine(md,s)}${el}`:'';
    const cmpRows=CHAR_K.filter(k=>C.W[k]>0).map(k=>{const r=C.by[k],tone=r>=1.05?'good':r<0.95?'bad':'muted';return `<div class="cmp-row"><span>${CHAR_NAMES[k]}<small>${wDots(C.W[k])}</small></span><div class="cmp-bar"><i style="width:${Math.min(100,r/2*100)}%;background:var(--${tone==='muted'?'line':tone})"></i><b></b></div><span class="num ${tone}">${Math.round(r*100)}%</span></div>`;}).join('');
    // заголовок: картинка, название (цвет — как машина против соперников), класс, итог месяца
    const sub=md.status==='prod'?`спрос ${fmtD(md.lastDem||0)} · продано ${fmtN(md.lastSold||0)} · маржа ${money(margin)}`:md.status==='dev'?`в разработке ещё ${md.devLeft} мес.`:md.status==='sale'?`на складе ${fmtN(md.stock)}`:`всего продано ${fmtN(md.totalSold)}`;
    const head=`<span class="mh"><span class="mthumb">${carArt(md,{thumb:1})}</span><span class="mt"><b class="${TT.tone}">${md.legend?'★ ':''}${esc(md.name)}</b><small>${esc(KIND_NAME[rivalKind(md)])} · ${Math.round(TT.r*100)}% соперника</small><small>${sub}</small></span></span>${pill}`;
    const body=open?`
      ${ctl}
      <div class="meta"><div>Спрос<b>${md.status==='prod'?fmtD(md.lastDem):'—'}</b></div><div>Продано<b>${md.status==='prod'?fmtN(md.lastSold):'—'}</b></div><div>Себест.<b>${money(uc)}</b></div><div>Маржа<b class="${margin<0?'bad':''}">${money(margin)}</b></div></div>
      ${lostLine(md)}${truckHint(md,s)}${costHTML(md,s)}${stockWarn(md)?'<p class="small warn" style="margin-top:6px">Машины копятся на складе и дешевеют: снизьте выпуск или цену.</p>':''}
      <div class="carbox${enter}">${carArt(md,{anim:md.status==='prod'})}</div>${carGallery(md)}
      ${qbar(C.S,'Против соперника: '+C.ref.name)}
      ${fold('cmp'+md.id,'Что ценят покупатели',`<div>${cmpRows}</div><p class="small muted" style="margin-top:6px">●●● — главное для покупателей класса. 100% — как у соперника. Улучшения в КБ поднимают эти цифры у всех ваших машин.</p>`,false)}
      <p class="spec">${specLine(md,s)}</p>
      ${(md.raceBoost||0)>mi(s)?'<p class="small good" style="margin-top:6px">Слава гоночной победы: покупатели выбирают вас охотнее</p>':''}
      ${md.legend&&LEGEND_BY[md.legend]?`<p class="small good" style="margin-top:6px">★ Легенда марки: ${esc(legendFxText(LEGEND_BY[md.legend]))}</p>`:''}${md.acq?`<p class="small muted" style="margin-top:6px">🤝 Модель купленной марки «${esc(md.acq)}»: продаётся ${md.only&&COUNTRIES[md.only]?`только в стране «${esc(COUNTRIES[md.only].name)}» — через её дилеров`:'под её именем'}.</p>`:''}
      ${overpower(md)?'<p class="small bad" style="margin-top:6px">Мотор слишком мощный для рамы: поломки бьют по репутации.</p>':''}
      <div class="row small muted" style="margin-top:10px"><span>Всего продано</span><span class="num">${md.totalSold.toLocaleString('ru-RU')}</span></div>
      ${md.status==='prod'?`<div class="btns" style="margin-top:12px"><button class="btn" data-act="retire" data-id="${md.id}">Снять с производства</button></div>`:''}
      ${md.status==='sale'?`<div class="btns" style="margin-top:12px"><button class="btn" data-act="saleNow" data-id="${md.id}">Отдать остаток перекупщикам (−50%)</button></div>`:''}
      ${md.status==='off'?`<div class="btns" style="margin-top:12px"><button class="btn" data-act="revive" data-id="${md.id}">Вернуть в производство</button></div>`:''}`:ctl;
    return `<article class="card mcard${open?'':' folded'}"><button class="card-h" data-act="fold" data-k="${key}" data-def="${!many||md.status==='dev'?1:0}" aria-expanded="${open}">${head}<i>${open?'▴':'▾'}</i></button>${body}</article>`;};
  const L=s.models.slice().sort((a,b)=>ord[a.status]-ord[b.status]||b.id-a.id),live=L.filter(m=>m.status!=='off'),off=L.filter(m=>m.status==='off');
  const offCard=off.length?foldCard('offmodels',false,`<h2>Снятые</h2><span class="label">с производства · ${off.length}</span>`,`<div class="offlist">${off.map(card).join('')}</div>`,off.map(m=>esc(m.name)).join(', ')):'';
  return `${advisorCard(s,'models')}${planCard(s)}${rdCardHTML(s)}<button class="btn primary block" data-act="design">+ Новая модель</button>${legendCardHTML(s)}<p class="small muted" style="padding:0 4px">Похожие модели одной марки отбирают покупателей друг у друга: выгоднее разные машины для разных классов, чем несколько одинаковых. Нажмите на модель, чтобы развернуть или свернуть описание.</p>${live.map(card).join('')}${ordersCard(s)}${offCard}`;
}
function techRows(arr,s,extra){return arr.map(x=>`<div class="tech ${x.y<=s.y?'':'off'}"><span class="num">${x.y<=1895?'—':x.y}</span><span>${x.name}</span><span class="num">${extra(x)}</span></div>`).join('');}
// Сколько продавали бы ваши модели в стране при полной сети дилеров
function marketPotential(s,c){const act=s.models.filter(m=>m.status==='prod'&&(!m.only||m.only===c));if(!act.length||(c!==s.country&&warCut(s,c)))return 0;const R=mkCountry(c,s,act,null,null,1);return act.reduce((a,m)=>a+(R.by[m.id]||0),0)*(techLv(s,'credit')?1.15:1);}
function topIncome(inc,p){return inc.xT*Math.pow(p/INC_TOP,-1/inc.al);}
// 0.26: грузовые перевозки: три рынка — по району, по городу, между городами; лошадь — только пока её ещё берут
function horseSplit(s,c,M,R0){const TZ=M&&M.segs&&M.segs.truck,pool=(M&&M.tpool)||(R0||mkCountry(c,s,[])).segs.truck.pool||0;if(pool<=0)return null;
  const you=TZ?TZ.you:0,riv=TZ?Math.max(0,TZ.size-TZ.you):(R0||mkCountry(c,s,[])).segs.truck.inc;return {pool,you,riv,horse:Math.max(0,pool-riv-you)};}
function horseHTML(s,c,M,R0){if(s.y<1896)return '';const Rx=R0||mkCountry(c,s,[]),uses=(M&&M.tuse)||Rx.segs.truck.uses;if(!uses)return '';
  let pool=0,riv=0,you=0;TUSE.forEach(u=>{const z=uses[u];if(z){pool+=z.pool;riv+=z.riv;you+=z.you;}});if(pool<=0)return '';
  const horse=Math.max(0,pool-riv-you),pp=x=>pct(x,x<0.1?1:0);
  const rows=TUSE.filter(u=>uses[u]&&uses[u].pool>0.05).map(u=>{const z=uses[u],h=Math.max(0,z.pool-z.riv-z.you),w=x=>Math.max(0,Math.min(100,x/z.pool*100));
    return `<div style="margin-top:8px"><div class="row small"><span><b>${TRUCK_USE[u].n}</b> <span class="muted">· ${esc(TRUCK_USE[u].who)}</span></span><span class="muted">${fmtD(z.pool)} фирм</span></div>
      <div class="hbar" style="margin-top:4px">${h/z.pool>0.02?`<i style="width:${w(h)}%;background:#9a7448"></i>`:''}<i style="width:${w(z.riv)}%;background:#6f8aa6"></i><i style="width:${w(z.you)}%;background:var(--brass)"></i></div></div>`;}).join('');
  return `<div style="margin-top:14px"><div class="row small"><span class="label">🚚 Кто покупает грузовые машины</span><span class="muted">фирм в месяц ≈ ${fmtD(pool)}</span></div>${rows}
    <div class="hleg small">${horse/pool>0.02?`<span><i style="background:#9a7448"></i>лошадь ${pp(horse/pool)}</span>`:''}<span><i style="background:#6f8aa6"></i>конкуренты ${pp(riv/pool)}</span><span><i style="background:var(--brass)"></i>ваши ${pp(you/pool)}</span></div>
    <p class="small muted" style="margin-top:6px">Каждой перевозке — своя машина: лавке, которая развозит хлеб, нужен фургон, мебель по городу возят на полуторатонке, большие партии между городами — на трёхтонке. Фирма выбирает по цене тонно-километра: машина за годы службы, ремонт и простои, бензин, шофёр.${horse/pool>0.02?' Пока мотор не выгоднее, часть фирм берёт лошадь.':' Лошадей фирмы уже почти не покупают.'}</p></div>`;}
// 0.29: доли рынка — дома, в каждой стране и во всём мире: ваши продажи против марок-конкурентов (за прошлый год;
// в первый год — с начала года). Конкуренция идёт на всех пяти рынках: в каждой стране — свои марки и свой спрос.
const WORLD_NAME={'Ford (Манчестер)':'Ford'};
function sharesData(s,sel){const cs=Object.keys(COUNTRIES),full=Object.keys(s.mPrev||{}).length>0,val=o=>full?(o.prev||0):(o.yr||0);
  const mine=c=>full?((s.cPrev||{})[c]||0):((s.cY||{})[c]||0),mkt=c=>full?((s.mPrev||{})[c]||0):((s.mY||{})[c]||0);
  const one=c=>{const L=(COMPS[c]||[]).map((cp,i)=>({cp,i})).filter(o=>o.cp.pk!==s.pioneer&&!acqHas(s,c,o.i)).map(o=>{const st=(s.comps[c]||[])[o.i]||{};return {n:compName(o.cp,s),v:val(st),color:st.color||'#888',c};}).filter(r=>r.v>0.5);
    L.push({n:s.company,v:mine(c),you:1,c});const tot=Math.max(mkt(c),L.reduce((a,r)=>a+r.v,0)),sum=L.reduce((a,r)=>a+r.v,0);if(tot-sum>0.5)L.push({n:'Мелкие марки и импорт',v:tot-sum,rest:1,c});return {L:L.sort((a,b)=>b.v-a.v),tot};};
  if(sel!=='world')return Object.assign(one(sel),{full});
  const M=new Map();let tot=0;cs.forEach(c=>{const D=one(c);tot+=D.tot;D.L.forEach(r=>{const k=r.you?'__you':r.rest?'__rest':(WORLD_NAME[r.n]||r.n);let o=M.get(k);if(!o){o={n:r.you?s.company:r.rest?'Мелкие марки и импорт':(WORLD_NAME[r.n]||r.n),v:0,you:r.you,rest:r.rest,color:r.color,cs:[]};M.set(k,o);}o.v+=r.v;if(r.v>0.5&&!o.cs.includes(c))o.cs.push(c);});});
  return {L:[...M.values()].sort((a,b)=>b.v-a.v),tot,full};}
function sharesCard(s){const cs=Object.keys(COUNTRIES),sel=(s.ui&&s.ui.mkC)||'world',D=sharesData(s,sel),tot=Math.max(1,D.tot);
  const named=D.L.filter(r=>!r.rest),place=named.findIndex(r=>r.you)+1,show=named.slice(0,8);if(place>8)show.push(named[place-1]);const rest=D.L.find(r=>r.rest);if(rest)show.push(rest);
  const mx=Math.max(1,...show.map(r=>r.v)),me=D.L.find(r=>r.you)||{v:0};
  const chip=(k,lab)=>{const d=k==='world'?null:sharesData(s,k),sh=k==='world'?null:(d.L.find(r=>r.you)||{v:0}).v/Math.max(1,d.tot);return `<button class="chip ${sel===k?'on':''}" data-act="mkC" data-v="${k}">${lab}${sh!==null?`<small>вы ${pct(sh,sh<0.1?1:0)}</small>`:''}</button>`;};
  const rows=show.map(r=>`<tr class="${r.you?'you':''}"><td>${r.rest?'':(named.indexOf(r)+1)+'.'}</td><td>${esc(r.n)}${sel==='world'&&!r.you&&!r.rest&&r.cs&&r.cs.length?`<small>${r.cs.map(c=>COUNTRIES[c].name).join(', ')}</small>`:''}</td><td style="width:34%"><div class="bar"><i style="width:${r.v/mx*100}%;background:${r.you?'var(--brass)':r.rest?'var(--line)':(r.color||'#888')}"></i></div></td><td class="n">${fmtN(r.v)}</td><td class="n sh">${pct(r.v/tot,r.v/tot<0.1?1:0)}</td></tr>`).join('');
  const what=sel==='world'?'во всём мире (пять рынков)':COUNTRIES[sel].name+(sel===s.country?' — дома':'');
  const body=`<p class="small muted" style="margin-top:2px">Продано машин ${D.full?`за ${s.y-1} год`:'с начала года'} ${what}. На каждом рынке — свои марки и свой спрос: за границей вы соревнуетесь с местными марками этой страны${sel!=='world'&&sel!==s.country&&!dealerCount(s,sel)?'. Своих дилеров здесь пока нет — продаж тоже':''}.</p>
    <div class="chips sm" style="margin-top:8px">${chip('world','Мир')}${cs.map(c=>chip(c,COUNTRIES[c].name)).join('')}</div>
    <table class="pl shares-t" style="margin-top:8px"><tr><th></th><th>Марка</th><th></th><th class="n">Машин</th><th class="n sh">Доля</th></tr>${rows}</table>
    <p class="small" style="margin-top:6px">Вы — <b>${place||'—'}-е</b> ${sel==='world'?'в мире':'на этом рынке'}: ${fmtN(me.v)} из ${fmtN(D.tot)} машин (${pct(me.v/tot,me.v/tot<0.1?1:0)}).</p>`;
  const wd=sharesData(s,'world'),wme=wd.L.find(r=>r.you)||{v:0},wpl=wd.L.filter(r=>!r.rest).findIndex(r=>r.you)+1;
  return foldCard('shares',true,`<h2>Доли рынка</h2><span class="pill ${wpl&&wpl<=3?'good':'muted'}">мир: ${wpl||'—'}-е</span>`,body,`мир: вы ${wpl||'—'}-е, ${pct(wme.v/Math.max(1,wd.tot),1)} · ${cs.filter(c=>((D.full?(s.cPrev||{}):(s.cY||{}))[c]||0)>0).map(c=>{const d=sharesData(s,c),m=d.L.find(r=>r.you)||{v:0};return COUNTRIES[c].name+' '+pct(m.v/Math.max(1,d.tot),1);}).join(' · ')}`);}
function vMarket(){
  const s=G,home=s.country,e=econ(s.y,s.m,home),L=s.last,M=L&&L.mk[home],R0=mkCountry(home,s,[]),H=R0.H,inc=R0.inc,fleet=fleetOf(s,home),K=affordK(home,s);
  const segRows=SEGK.filter(g=>g!=='sport'||sportOpen(s,home)).map(g=>{const z=M&&M.segs?M.segs[g].size:R0.segs[g].inc,you=M&&M.segs?M.segs[g].you:0;return `<tr><td>${SEG[g].name}</td><td class="n">${fmtD(z)}</td><td class="n">${M?fmtD(you):'—'}</td><td class="n">${M&&z>0?pct(you/z,1):'—'}</td><td class="n">${money(prefP(g,home,s))}</td></tr>`;}).join('');
  const afford=CARSEG.filter(g=>g!=='sport'||sportOpen(s,home)).map(g=>{const P=prefP(g,home,s),n=canAfford(home,s,P),sh=n/H;return `<tr><td>${SEG[g].name} <small>≈ ${money(P)}</small></td><td class="n">${fmtN(n)}</td><td class="n">${pct(sh,sh<0.01?2:1)}</td></tr>`;}).join('');
  const top=s.models.filter(m=>m.status==='prod').sort((a,b)=>b.lastSold-a.lastSold)[0],full=(s.homePrev||0)>0||(s.comps[home]||[]).some(o=>(o.prev||0)>0);
  // продажи за прошлый год (в первый год — с начала года) и перемена к позапрошлому
  const val=o=>full?(o.prev||0):(o.yr||0),tr=o=>full&&(o.prev2||0)>0?o.prev/o.prev2-1:null;
  const rows=[{name:s.company,color:'var(--brass)',sales:full?(s.homePrev||0):(s.homeY||0),trend:full&&(s.homePrev2||0)>0?s.homePrev/s.homePrev2-1:null,you:1,model:top?top.name:''},...(COMPS[home]||[]).map((cp,i)=>({cp,i})).filter(o=>o.cp.pk!==s.pioneer&&compAlive(o.cp,s)).map(o=>{const m=compModel(o.cp,s),st=(s.comps[home]||[])[o.i]||{};return {name:compName(o.cp,s),color:st.color||'#888',sales:val(st),trend:tr(st),model:m?m[1]:'',img:m&&m[2],cp:o.cp,ci:o.i};})].sort((a,b)=>b.sales-a.sales);
  const place=rows.findIndex(r=>r.you)+1,shown=rows.slice(0,10);if(place>10)shown.push(rows[place-1]);
  const mx=Math.max(1,...rows.map(r=>r.sales)),arrow=t=>t===null?'':t>0.05?`<small class="good">▲${Math.round(t*100)}%</small>`:t<-0.05?`<small class="bad">▼${Math.round(-t*100)}%</small>`:'<small class="muted">≈</small>';
  // у каждой марки — снимок эпохи или рисунок её типичной машины; нажмите — история марки
  const comp=shown.map(r=>{const th=r.img&&IMG[r.img]?`<img class="thumb" src="${IMG[r.img].src}" alt="" loading="lazy" referrerpolicy="no-referrer">`:r.cp?compArt(r.cp,s,160):`<span class="dot" style="background:${r.color}"></span>`,inner=`${th}<span>${esc(r.name)}${r.model?`<small>${esc(r.model)}</small>`:''}</span><div class="bar"><i style="width:${r.sales/mx*100}%;background:${r.color}"></i></div><span class="num" style="text-align:right">${fmtN(r.sales)}${arrow(r.trend)}</span>`;
    return r.cp?`<button class="comp" data-act="brand" data-c="${home}" data-i="${r.ci}" aria-label="История марки ${esc(r.name)}">${inner}</button>`:`<div class="comp ${r.you?'you':''}">${inner}</div>`;}).join('');
  const rvT=SEGK.map(g=>{const v=rivalBoost(s,home,g);return v>0.05?`<span class="nw">${SEG[g].name.toLowerCase()} — ${rvWord(v)} <span class="num" title="сила ответа">${rvBar(v)}</span></span>`:'';}).filter(Boolean).join(', ');
  const dc=dealerCost(s),netRow=c=>{const d=dealerCount(s,c),need=Math.round(dealerNeed(c,s)),mx=dealerMax(s,c),lv=impLv(s,c),IL=impOf(s,c),ec=econ(s.y,s.m,c),mk=L&&L.mk[c],size=mk&&mk.size!=null?mk.size:SEGK.reduce((a,g)=>a+mkCountry(c,s,[]).segs[g].inc,0),tf=c===home?0:tariffOf(s.models.find(m=>m.status==='prod')||null,c,s),pot=marketPotential(s,c),lost=mk&&mk.lostDlr||0;
    // сколько городов охвачено; сколько машин в месяц продаёт сеть (дилеры растут вместе со спросом — нанимают продавцов)
    const room=dealerRoom(s,c),reach=reachOf(s,c),tp=dealerTPc(s,c),cap=d*tp,short=dealersShort(s,c),gs=room>0?0:dealerGrowSteps(s,c),gc=dealerGrowCost(s,c);
    const add=(n,lab,pri)=>{const k=Math.min(n,room);return k<1?'':`<button class="btn sm${pri?' primary':''}" data-act="dealers" data-c="${c}" data-n="${k}" ${s.cash<k*dc?'disabled':''}>+${fmtN(k)}${lab||''} · ${money(k*dc)}</button>`;};
    const cut=c!==home&&warCut(s,c);
    const big=Math.max(5,Math.round(mx*0.1/5)*5),bld=c!==home&&impBuilding(s,c),lic=c!==home&&s.lic&&s.lic[c],nx=!lic&&!bld&&lv<4?IMP_LV[lv+1]:null,nxC=nx?impCost(s,c,lv+1):0,nxOk=nx&&(!nx.y||s.y>=nx.y)&&!cut&&!(tradeBan(s,c)&&lv+1<3),mo=nx?impMonths(s,c,lv+1):0;
    const upLab=['Договор с импортёром','Открыть своё отделение','Сборка из комплектов','Построить свой завод'][lv];
    const up=c===home||!nx?'':`<button class="btn sm${lv===0?' primary':''}" data-act="impUp" data-c="${c}" ${!nxOk||s.cash<nxC?'disabled':''}>${upLab} · ${money(nxC)}${mo?` · ${mo} мес.`:''}</button>`;
    const bo=c!==home&&!(s.bought&&s.bought[c])?brandOfferOf(s,c):null,bc=bo?brandCands(s,c).find(x=>x.i===bo.i):null,bp=bc?bo.price:0;
    const extra=c===home||cut?'':(bc?`<button class="btn sm primary" data-act="brandBuy" data-c="${c}" data-i="${bc.i}" ${s.cash<bp?'disabled':''}>Купить марку «${esc(compName(bc.cp,s))}» · ${money(bp)}</button>`:'')
      +(lic?`<button class="btn sm" data-act="licEnd" data-c="${c}">Отозвать лицензию</button>`:'')
      +(lv<2&&!lic&&!tradeBanHard(s,c)?`<button class="btn sm" data-act="licStart" data-c="${c}" ${s.cash<licCost(s,c)?'disabled':''}>Лицензия местному заводу · ${money(licCost(s,c))}</button>`:'')
      +(c==='uk'&&home!=='uk'&&s.y>=1904&&!(s.hub&&s.hub.ca)?`<button class="btn sm" data-act="hubStart" ${s.cash<hubCost(s)?'disabled':''}>Сборка в Канаде (льгота для стран Империи) · ${money(hubCost(s))}</button>`:'');
    const grow=d&&dealerGrowOk(s,c)&&(gs>0||room===0)?`<button class="btn sm${gs>0?' primary':''}" data-act="dealerGrow" data-c="${c}" ${s.cash<gc?'disabled':''}>Салоны дилеров +25% · ${money(gc)}</button>`:'';
    const btns=cut?'':(d?(short>0?add(short,' — продать всем',1)+(short>=8?add(Math.max(1,Math.round(short/4)),''):''):add(Math.max(1,Math.min(room,Math.round(mx*0.05))),room>1?' в новых городах':'')+(room>big*1.5?add(big):''))+grow:'')+up+extra;
    const R=c===home?null:ruleNow(s,c),rtxt=R?`<p class="small ${tradeBan(s,c)?'bad':R.quota?'warn':'muted'}" style="margin-top:4px">${tradeBan(s,c)?'⛔ ':''}${esc(R.why)}${R.quota&&!localMade(s,c)?` · квота ${fmtN(R.quota)} машин в год${s.quotaY&&s.quotaY[c]?`, продано ${fmtN(s.quotaY[c])}`:''}`:''}${c==='uk'&&hubOn(s,'ca')&&R.pref?' · ваши машины идут из Канады по льготе Империи (2/3 ставки)':''}</p>`:'';
    // 0.23: за блокадой — коротко и ясно, почему продаж нет и что будет дальше
    const cutTxt=cut?`<p class="small bad" style="margin-top:4px">⛔ Блокада: ${home==='de'?'немецким машинам за границу не пробиться — морские пути закрыты британским флотом.':`ни машин, ни деталей, ни денег в Германию не провезти — британский флот закрыл её моря.`}${(s.bought&&s.bought[c])?` Ваша марка «${esc(s.bought[c].n)}» отрезана: её заводы работают сами по себе под надзором властей, вам — ни машин, ни выручки до конца войны.`:lv>=3?` Ваш ${lv>=4?'завод':'цех сборки'} отрезан: работает на нужды страны, вам — ни выручки, ни связи до конца войны.`:dealerCount(s,c)?' Дилеры остались без машин.':''}${home!=='de'&&home!=='uk'&&home!=='fr'&&home!=='it'?` Если ваша страна вступит в войну с Германией — всё, что там ваше, конфискуют.`:''} Торговля вернётся летом 1919 года.</p>`:'';
    const boTxt=bc?`<p class="small good" style="margin-top:4px">🤝 Марка «${esc(compName(bc.cp,s))}» продаётся${bo.disc<1?` на ${Math.round((1-bo.disc)*100)}% дешевле обычного`:''} — до ${MONTHS[(bo.until%12+12)%12]} ${1895+Math.floor(bo.until/12)}: её заводы, дилеры и покупатели станут вашими, пошлины не будет. Это другой путь на рынок — вместо импортёра и отделения.</p>`:'';
    const lvTxt=c===home?'':boTxt+cutTxt+(bld?`<p class="small warn" style="margin-top:4px">${cut||bld.frozen?`Стройка заморожена блокадой: ${esc(IMP_LV[bld.lv].n.toLowerCase())} — осталось ${bld.left} мес. после войны`:`Строится: ${esc(IMP_LV[bld.lv].n.toLowerCase())} — ещё ${bld.left} мес.`}</p>`:'')+(lic?`<p class="small good" style="margin-top:4px">Лицензия: ${lic.at>mi(s)?`местный завод начнёт выпуск через ${lic.at-mi(s)} мес.`:`местный завод делает ваши машины — без пошлины и доставки, вам ${Math.round(LIC_ROY*100)}% цены с каждой`}.</p>`:'')
      +(s.bought&&s.bought[c]&&!cut?`<p class="small good" style="margin-top:4px">Ваша марка «${esc(s.bought[c].n)}»: местные заводы, дилеры и покупатели. Пошлины нет.</p>`:'')
      +(cut?'':lic&&lv>=1?`<p class="small muted" style="margin-top:4px">Пока действует лицензия, своё отделение, сборку и завод здесь не открыть: машины делает местный завод. Хотите строить своё — отзовите лицензию (кнопка ниже).</p>`:lv===0?`<p class="small" style="margin-top:4px">Своих продавцов здесь нет. Первый шаг — <b>импортёр</b>: местная фирма берёт ${Math.round(IMP_LV[1].cut*100)}% цены и продаёт ваши машины через агентов в больших городах${pot>0?`. По прикидке ваши модели брали бы здесь ≈ <b class="num">${fmtD(pot*Math.pow(IMP_LV[1].cap,0.7))}</b> в месяц`:''}. Или — <b>лицензия</b> местному заводу: почти даром, без пошлины, но вам лишь ${Math.round(LIC_ROY*100)}% цены.</p>`
      :lv===1?`<p class="small muted" style="margin-top:4px">Импортёр берёт ${Math.round(IL.cut*100)}% цены и торгует только в больших городах (до ${fmtN(mx)} агентов). <b>Своё отделение</b> — как Ford of Britain в 1909 году: без посредника, дилеры по всей стране, содержание ${money(impUpkeep({...s,imp:{...(s.imp||{}),[c]:2}},c))} в месяц.</p>`
      :lv===2?`<p class="small muted" style="margin-top:4px">Своё отделение «${esc(s.company)}». ${s.y>=IMP_LV[3].y?`<b>Сборка из комплектов</b> — как у Ford в Траффорд-парке (1911): пошлина только на детали (${Math.round(IMP_LV[3].tar*100)}% ставки), доставка вдвое дешевле, покупатели считают машины почти своими; содержание ${money(impUpkeep({...s,imp:{...(s.imp||{}),[c]:3}},c))} в месяц, нужен объём.`:'Сборка за границей появится с 1904 года.'}</p>`
      :lv===3?`<p class="small good" style="margin-top:4px">Сборка из комплектов: пошлина ${pct(tf,0)}, доставка вдвое дешевле. ${s.y>=IMP_LV[4].y?`<b>Свой завод</b> — пошлины и доставки нет совсем, машины для покупателей местные; но в войну завод противника конфискуют.`:''}</p>`
      :`<p class="small good" style="margin-top:4px">Свой завод «${esc(s.company)}»: без пошлины и доставки, для покупателей — местная марка.</p>`)+rtxt;
    // 0.26: доля в стране по классам; цена здесь (наценка к домашней) и что остаётся с машины
    const shTxt=mk&&mk.size>0?(()=>{const g=SEGK.filter(g=>mk.segs&&mk.segs[g]&&mk.segs[g].you>0.4).map(g=>`${SEG[g].name.toLowerCase()} ${pct(mk.segs[g].you/Math.max(1e-9,mk.segs[g].size),mk.segs[g].you/mk.segs[g].size<0.1?1:0)}`);return `<p class="small" style="margin-top:4px">Доля рынка: <b class="num">${pct((mk.sold||0)/Math.max(1,mk.size),(mk.sold||0)/mk.size<0.1?1:0)}</b>${g.length?` <span class="muted">· ${g.join(' · ')}</span>`:''}</p>`;})():'';
    const top3=c===home||!d||cut?[]:s.models.filter(m=>m.status==='prod'||m.status==='sale').sort((a,b)=>((b.soldBy&&b.soldBy[c])||0)-((a.soldBy&&a.soldBy[c])||0)).slice(0,3);
    const pmTxt=c===home||!d||cut||tradeBan(s,c)?'':`<div class="small pmk-row"><span class="muted">Цена здесь — к цене дома:</span><div class="chips sm">${PMK.map(([k,lab])=>`<button class="chip ${Math.abs(pmkOf(s,c)-k)<1e-6?'on':''}" data-act="pmk" data-c="${c}" data-v="${k}">${lab}</button>`).join('')}</div></div>`
      +(top3.length?`<p class="small muted" style="margin-top:4px">${top3.map(m=>{const n=netPer(m,c,s),mg=licOn(s,c)?n:n-unitCost(m,s);return `«${esc(m.name)}»: покупатель ${money(offerPrice(m,c,s))}, вам ${money(n)}, маржа <b class="${mg<0?'bad':'good'}">${money(mg)}</b>`;}).join(' · ')}</p>`:'');
    // 0.29: каждую страну можно свернуть — остаётся строка: рынок, продажи, дилеры
    const fk='net_'+c,fo=isOpen(fk,c===home||d>0);
    const head=`<button class="net-h" data-act="fold" data-k="${fk}" data-def="${c===home||d>0?1:0}" aria-expanded="${fo}"><div class="row"><div><h3>${COUNTRIES[c].name}${c===home?' · дома':''}${c!==home?` <span class="pill ${lv?'good':'muted'}">${esc(lic?'Лицензия':(s.bought&&s.bought[c])?'Своя марка':IMP_LV[lv].n)}</span>`:''}</h3><p class="small muted">Рынок ${fmtD(size)} в месяц · <span class="${ec.tone}">${ec.label}</span>${c!==home?(cut?' · <span class="bad">блокада</span>':tradeBan(s,c)?' · <span class="bad">ввоз закрыт</span>':` · пошлина ${Math.round(tf*100)}%`):''}${fo?'':` · дилеров ${fmtN(d)}${mk&&mk.size>0?` · доля ${pct((mk.sold||0)/Math.max(1,mk.size),1)}`:''}`}</p></div><span class="num small ${mk&&mk.sold?'good':''}" style="white-space:nowrap">${mk?fmtN(mk.sold||0):0} шт. <i class="muted">${fo?'▴':'▾'}</i></span></div></button>`;
    if(!fo)return `<div class="net-row folded">${head}</div>`;
    return `<div class="net-row">${head}
      ${lvTxt}${c===home?'':shTxt}${pmTxt}
      ${d&&!cut?`${pot>0?`<p class="small" style="margin-top:4px">Будь ваши дилеры во всех городах, ваши модели брали бы ≈ <b class="num">${fmtD(pot)}</b> в месяц · сейчас их видят ${Math.round(reach*100)}% покупателей</p>`:''}
      <div class="row small" style="margin-top:6px"><span class="muted">Дилеров <b class="num">${fmtN(d)}</b> из ${fmtN(mx)} ${plural(mx,'возможного','возможных','возможных')} · вся страна — ${fmtN(need)} ${plural(need,'город','города','городов')}</span><span class="num">${Math.round(reach*100)}%</span></div><div class="bar" style="margin-top:4px"><i style="width:${Math.min(100,reach*100)}%;background:var(--good)"></i></div>
      <p class="small muted" style="margin-top:4px">Сеть продаёт до ${fmtN(cap)} машин в месяц — по ${fmtD(tp)} на дилера${dealerMult(s,c)>1.01?` (салоны больше обычного в ${fmtD(dealerMult(s,c))} раза)`:''}.</p>
      ${lost>0.5?`<p class="small warn" style="margin-top:4px">Дилеры не успели обслужить ≈ ${fmtD(lost)} покупателей. ${short>0?`Откройте дилеров в новых городах — ещё ${fmtN(short)}.`:gs>0?`Все города уже охвачены: расширьте салоны — продавцы, гаражи, запас машин (${fmtN(gs)} ${plural(gs,'шаг','шага','шагов')} по +25%).`:'Сеть работает на пределе эпохи: больше машин здесь сейчас не продать.'}</p>`:''}`:''}
      <div class="btns" style="margin-top:6px">${btns}${d>(c===home?1:2)?`<button class="btn sm" data-act="dealersCut" data-c="${c}">Закрыть 20%</button>`:''}${promoOk(s,c)?`<button class="btn sm" data-act="promoSheet" data-c="${c}">📣 Спецакции${(s.promo||[]).some(p=>p.c===c&&p.until>mi(s))?' · идут':''}</button>`:''}</div></div>`;};
  const abroad=Object.keys(COUNTRIES).filter(c=>c!==home),nAb=abroad.filter(c=>dealerCount(s,c)>0).length;
  const net=netRow(home)+fold('exp','Экспорт: '+(nAb?`дилеры в ${nAb} ${plural(nAb,'стране','странах','странах')}`:'пока нет'),abroad.map(netRow).join(''),nAb>0,'за границей покупатель платит пошлину, а вы — доставку');
  return `${advisorCard(s,'market')}${chalCard(s,'market')}${foldCard('mkhome',true,`<h2>${COUNTRIES[home].name}</h2><span class="pill ${e.tone}">${e.label}</span>`,`
    <div class="meta"><div>Рынок/мес<b>${fmtD(M&&M.size?M.size:SEGK.reduce((a,g)=>a+R0.segs[g].inc,0))}</b></div><div>Ваши<b>${L?fmtN(L.homeSold):'—'}</b></div><div>Доля<b>${L?pct(L.share,1):'—'}</b></div><div>Цены к 1913<b>${Math.round(cpi(s)*100)}%</b></div></div>${home==='us'&&s.y<1905?'<p class="small warn" style="margin-top:8px">Богатых семей в Америке много, но дороги плохи, и машины пока берут неохотно. Во Франции машины уже в моде: откройте там дилеров ниже, пошлина невелика.</p>':''}${home==='it'&&s.y<1905?'<p class="small warn" style="margin-top:8px">Богатых семей в Италии мало, свой рынок крошечный. Продавайте и за границей: во Франции покупателей в разы больше, пошлина — 12%.</p>':''}<div class="hr"></div>
    <table class="pl"><tr><th>Класс</th><th class="n">Рынок</th><th class="n">Вы</th><th class="n">Доля</th><th class="n">Цена</th></tr>${segRows}</table>
    <p class="small muted" style="margin-top:10px">Сколько машин купили в прошлом месяце у всех марок и у вас. Весной и летом покупают охотнее. Класс машины задают кузов и оснащение; цена — типичная для класса. Грузовые машины берут фирмы и ведомства: для своих перевозок они выбирают машину, на которой дешевле тонно-километр.</p>${horseHTML(s,home,M,R0)}`,`рынок ${fmtD(M&&M.size?M.size:SEGK.reduce((a,g)=>a+R0.segs[g].inc,0))} в месяц · ваши ${L?fmtN(L.homeSold):'—'} · доля ${L?pct(L.share,1):'—'}`)}
  ${sharesCard(s)}
  ${dealsCard(s)}
  ${foldCard('buyers',false,'<h2>Покупатели</h2>',`
    <div class="meta"><div>Семей<b>${fmtN(H)}</b></div><div>Доход семьи<b>${money(inc.med)}</b></div><div>Машин на дорогах<b>${fmtN(fleet)}</b></div><div>С машиной<b>${pct(Math.min(1,fleet/H),fleet/H<0.01?2:1)}</b></div></div>
    <p class="small muted" style="margin-top:6px">Доход — у средней семьи за год: половина семей беднее. Богатейшие 1% получают от ${money(topIncome(inc,0.01))} в год.</p>
    <table class="pl" style="margin-top:10px"><tr><th>Машина по карману</th><th class="n">Семей</th><th class="n">Доля</th></tr>${afford}</table>
    <p class="small muted" style="margin-top:8px">Машина по карману, если стоит не больше ${pct(K,0)} годового дохода семьи${K>0.5?' — помогает рассрочка':''}. Каждый месяц к машине присматривается часть семей: новички и владельцы, которые меняют старую. Берут то, что лучше за свои деньги, или ждут. Чем дешевле хорошая машина, тем больше семей может её купить.</p>`,`семей ${fmtN(H)} · с машиной ${pct(Math.min(1,fleet/H),fleet/H<0.01?2:1)}`)}
  ${foldCard('comps',false,`<h2>Конкуренты</h2><span class="pill ${place<=3?'good':'warn'}">вы ${place}-е</span>`,`<p class="small muted" style="margin-top:2px">Реальные марки эпохи и их модели. Продано машин ${full?`за ${s.y-1} год, стрелка — к ${s.y-2} году`:'с начала года'}. Нажмите на марку — её история.</p><div style="margin-top:8px">${comp}</div>
    ${rvT?`<p class="small warn" style="margin-top:8px">Конкуренты отвечают на ваш успех — новинками, скидками и рекламой. Их машины стали привлекательнее: ${rvT}. Держите позиции новыми моделями, улучшениями и ценой.</p>`:`<p class="small muted" style="margin-top:8px">Если заберёте у конкурентов много покупателей, они ответят: новыми моделями, ценами и рекламой.</p>`}`,`вы ${place}-е · ${rows.slice(0,3).map(r=>esc(r.name)+' '+fmtN(r.sales)).join(' · ')}`)}
  ${showsCard(s)}
  ${worldCard(s)}
  ${foldCard('dealers',true,'<h2>Дилеры и экспорт</h2>',`<p class="small muted" style="margin-top:2px">Дилер — торговец в своём городе: покупает у вас машины со скидкой ${Math.round(dMargin(s)*100)}%, продаёт их и чинит. Где нет вашего дилера, там машину не купить; больше дилеров, чем городов с покупателями, не бывает. Первые дилеры открываются в больших городах и сразу видят большую часть покупателей. Когда спрос растёт, дилеры сами нанимают продавцов, а к марке, которая хорошо продаётся, новые города просятся сами. Новый дилер — ${money(dc)} (разъездные агенты, вывеска, демонстрационная машина), поддержка ${money(dealerUpkeep(s))} в месяц. За границей сначала нужен импортёр, потом своё отделение и сборочный завод; покупатель там платит пошлину, а вы — доставку (по Европе ${money(40*cpi(s))}, через Атлантику ${money(90*cpi(s))}). Пошлины меняются по годам — смотрите карту «Мир».</p>
    <div class="label" style="margin-top:10px">Скидка дилерам</div><div class="chips">${Object.entries(DPOL).map(([k,p])=>`<button class="chip ${(s.dpol||'std')===k?'on':''}" data-act="dpol" data-v="${k}">${p.n} · ${Math.round(p.m*100)}%<small>${p.d}</small></button>`).join('')}</div>
    <div style="margin-top:6px">${net}</div>`,`дома ${fmtN(dealerCount(s,home))} ${plural(dealerCount(s,home),'дилер','дилера','дилеров')} · покупателей видят ${Math.round(reachOf(s,home)*100)}%${nAb?` · за границей: ${nAb} ${plural(nAb,'страна','страны','стран')}`:''}`)}
  ${DIF().simple&&helperOn(s)?foldCard('adc',true,`<h2>Реклама</h2><b class="num">${money(s.ad)}</b>`,`<p class="small muted" style="margin-top:6px">Рекламой занимается помощник: около 4% выручки.</p>`,`${money(s.ad)} в месяц`):foldCard('adc',true,`<h2>Реклама</h2><b class="num" id="adVal">${money(s.ad)}</b>`,`<input type="range" id="ad" min="0" max="${Math.round(adRef(s)*4/10)*10}" step="${Math.max(10,Math.round(adRef(s)/50/10)*10)}" value="${s.ad}" aria-label="Бюджет рекламы в месяц" style="margin-top:10px"><p class="small muted">В месяц. Отдача падает после ${money(adRef(s)*2)}; за границей реклама работает на треть.</p>`,`${money(s.ad)} в месяц`)}
  ${foldCard('graphs',false,'<h2>Графики</h2>',`<div style="margin-top:8px"><span class="label">Объём рынка, машин в месяц</span>${spark(s.hist.market,'var(--muted)')}<div class="hr"></div><span class="label">Ваши продажи, машин в месяц</span>${spark(s.hist.sales,'var(--good)')}<div class="hr"></div><span class="label">Ваша доля дома, %</span>${spark(s.hist.share||[],'var(--brass)')}</div>`,'рынок, ваши продажи и доля по месяцам')}
  ${foldCard('sup',false,'<h2>Технологии поставщиков</h2>',`<p class="small muted" style="margin-top:4px">Какие детали можно купить и когда появятся новые. Серые — в будущем, их можно получить раньше прототипом КБ.</p>
    <div class="label" style="margin-top:6px">Двигатели</div>${techRows(ENGINES,s,x=>x.hp+' л.с.')}<div class="label" style="margin-top:12px">Коробки передач</div>${techRows(GEARBOX,s,x=>'КПД '+Math.round(x.eff*100)+'%')}<div class="label" style="margin-top:12px">Рамы и подвеска</div>${techRows(CHASSIS,s,x=>'до '+Math.round(x.max*bn('chassisTol'))+' л.с.')}<div class="label" style="margin-top:12px">Колёса и шины</div>${techRows(TYRES,s,x=>'сцепл. '+Math.round(x.grip*100))}<div class="label" style="margin-top:12px">Тормоза</div>${techRows(BRAKES,s,x=>'сила '+Math.round(x.brk*100))}<div class="label" style="margin-top:12px">Кузова</div>${techRows(BODIES,s,x=>x.truck?x.pay+' т':x.seats+' мест')}`,'какие детали можно купить и когда появятся новые')}`;
}
function legacyCard(){
  const s=G,t=legacyTable(s),me=t.me,maxes={scale:400,market:200,innov:240,sport:400,capital:250,brand:160};
  const bars=Object.keys(LEG_NAMES).map(k=>`<div class="leg-row"><span>${LEG_NAMES[k]}</span><div class="bar"><i style="width:${Math.min(100,me[k]/maxes[k]*100)}%;background:var(--brass)"></i></div><b class="num">${Math.round(me[k])}</b></div>`).join('');
  const near=t.rows.slice(Math.max(0,t.place-3),t.place+2).map((r,i)=>`<tr class="${r.you?'you':''}"><td>${t.rows.indexOf(r)+1}.</td><td>${esc(r.n)}</td><td class="n">${Math.round(r.L.total)}</td></tr>`).join('');
  const firsts=Object.values(s.firsts||{}).map(f=>`<li class="good"><time>${f.y}</time><p>${esc(f.name)} — раньше, чем ${esc(f.who)} (${f.hy})</p></li>`).join('');
  return `<section class="card" id="sec-legacy"><div class="row"><h2>Наследие</h2><span class="pill warn">${t.place}-е место</span></div>
    <p class="small muted" style="margin-top:4px">Цель игры — создать величайшую автоимперию эпохи. В 1930 году вашу компанию сравнят с реальными: Ford, General Motors, Citroën, FIAT, Bugatti, Rolls-Royce и другими — по масштабу, доле рынка, изобретениям, победам, капиталу и имени.</p>
    <div style="margin-top:10px">${bars}</div><div class="row small" style="margin-top:6px"><span class="muted">Всего очков</span><b class="num">${Math.round(me.total)}</b></div>
    <p class="small muted" style="margin-top:4px">У реальных компаний — итог к 1929 году. Ваши очки копятся годами: доля рынка — за каждый год, имя марки зреет лет двадцать (сейчас ${Math.round((me.mat||1)*100)}%), первенство засчитывается, когда новинка пошла в серию.</p>
    <table class="pl" style="margin-top:10px">${near}</table>
    ${humanLegacyHTML(s)}
    ${firsts?`<div class="label" style="margin-top:12px">Первенства</div><ul class="log">${firsts}</ul>`:'<p class="small muted" style="margin-top:10px">Первенств пока нет. Внедрите технологию или деталь раньше, чем это случилось в истории, — прокачайте КБ.</p>'}
    <button class="btn block" style="margin-top:10px" data-act="legacyInfo">Как считаются очки</button></section>`;
}
function vLog(){
  const got=ACH.filter(a=>G.ach[a.id]).length;
  const papers=G.papers.slice().reverse().map((p,i)=>`<button class="chip" style="width:100%;margin-top:6px" data-act="reopenPaper" data-k="${G.papers.length-1-i}"><small>${p.d}</small>${esc(p.title)}</button>`).join('');
  const last=G.papers[G.papers.length-1];
  return `<section class="card emp-head"><span class="label">Империя «${esc(G.company)}»</span><h2>Наследие — смысл игры</h2><p class="small muted" style="margin-top:4px">В 1930 году вашу компанию сравнят с настоящими: Ford, General Motors, Citroën, FIAT, Rolls-Royce, Bugatti. Очки дают масштаб, рынок, изобретения, победы, капитал и имя. Здесь же — титулы года, вызовы соперников и фильм о вашем герое.</p></section>
  ${legacyCard()}${titlesCard(G)}${boardCard(G)}${trophyCabinetCard(G)}${sagaCard(G)}${papers?foldCard('papers',false,'<h2>Газетный архив</h2>',papers,last?`${G.papers.length} ${plural(G.papers.length,'выпуск','выпуска','выпусков')} · последний: ${esc(last.title)}`:''):''}${reelsCard(G)}
  ${foldCard('ach',false,`<h2>Достижения</h2><span class="num muted">${got}/${ACH.length}</span>`,`<div class="ach">${ACH.map(a=>`<div class="${G.ach[a.id]?'got':''}"><b>${a.name}</b>${a.desc}${G.ach[a.id]?' · '+G.ach[a.id]:''}</div>`).join('')}</div>`,`получено ${got} из ${ACH.length}`)}
  ${foldCard('log',true,'<h2>Хроника</h2>',`<ul class="log" style="margin-top:6px">${G.log.slice().reverse().map(l=>`<li class="${l.kind}"><time>${l.d}</time><p>${esc(l.text)}</p></li>`).join('')}</ul>`,G.log.length?esc(G.log[G.log.length-1].d+': '+G.log[G.log.length-1].text):'')}`;
}
let shownCash=null,cashRaf=0,lastDate='';
// касса в шапке: от $10 млн — коротко («$22,1 млн», «$1,25 млрд»), чтобы шапка помещалась на узком экране
const moneyC=v=>{const a=Math.abs(v),sg=v<0?'−':'';return a>=1e9?sg+'$'+(a/1e9).toFixed(2).replace('.',',')+' млрд':a>=1e7?sg+'$'+(a/1e6).toFixed(a>=1e8?0:1).replace('.',',')+' млн':money(v);};
function setCash(v){const el=document.getElementById('cash');el.className=v<0?'neg':'';el.title=v<0?'Кредит банка исчерпан: минус — долг поставщикам и рабочим':money(v);{const lb=document.getElementById('cashLbl');if(lb)lb.textContent=v<0?'Долг':'Касса';}if(shownCash===null||REDUCE){shownCash=v;el.textContent=moneyC(v);return;}
  const from=shownCash,t0=performance.now();shownCash=v;cancelAnimationFrame(cashRaf);const tick=now=>{const k=Math.min(1,(now-t0)/600),e=1-Math.pow(1-k,3);el.textContent=moneyC(from+(v-from)*e);if(k<1)cashRaf=requestAnimationFrame(tick);};cashRaf=requestAnimationFrame(tick);}
// широкий экран в горизонтальном положении (Fold 7, планшет): витрина «Империя» — колонкой справа
function wideLand(){try{return matchMedia('(orientation:landscape) and (min-width:760px)').matches;}catch(_){return false;}}
function render(){
  const s=G;if(!s)return;if(s.mode==='racer'){racerRender(s);return;}racerNav();try{autoCredit(s);dealerFit(s);}catch(_){}
  document.getElementById('co').textContent=`${s.company} · ${COUNTRIES[s.country].city}`;
  const d=document.getElementById('date'),ds=dstr(s);d.innerHTML=`${MONTHS[s.m]} <span>${s.y}</span>`;
  if(lastDate&&lastDate!==ds){d.classList.remove('flip');void d.offsetWidth;d.classList.add('flip');}
  lastDate=ds;setCash(s.cash);
  document.getElementById('view').innerHTML=tab==='plant'?vPlant():tab==='models'?vModels():tab==='market'?vMarket():tab==='race'?vRace():vLog();
  {const es=document.getElementById('empStrip');if(es){es.innerHTML=empireStrip(s);es.hidden=tab==='log'&&!wideLand();es.classList.remove('flash');if(EC_FLASH&&!REDUCE){void es.offsetWidth;es.classList.add('flash');}}}
  document.body.dataset.tab=tab;
  if(tab==='plant')plantAnim();
  document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('on',b.dataset.t===tab));
  const nb=document.getElementById('nextBtn'),qb=document.getElementById('qBtn'),ab=document.getElementById('autoBtn');
  const blocked=s.pending.length>0||s.over;nb.disabled=qb.disabled=ab.disabled=blocked;
  nb.textContent=s.over?'Игра окончена':blocked?'Сначала решите событие':'Следующий месяц →';
  ab.textContent=auto?'❚❚':'▶';ab.classList.toggle('on',!!auto);
  const ad=document.getElementById('ad');if(ad)ad.addEventListener('input',e=>{G.ad=+e.target.value;document.getElementById('adVal').textContent=money(G.ad);save();});
  if(s.pending.length&&!R&&!evHold){stopAuto();showEvent();}
}
let toastQ=[],toastBusy=false;
function toast(msg){toastQ.push(msg);if(!toastBusy)nextToast();}
function nextToast(){const m=toastQ.shift(),el=document.getElementById('toast');if(!m){toastBusy=false;el.hidden=true;return;}toastBusy=true;el.textContent=m;el.hidden=false;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');setTimeout(nextToast,auto?1000:2200);}
function afterStep(){const L=G.last;if(L){toastQ=toastQ.slice(-1);toast(`${L.label}: продано ${fmtN(L.sold)} · ${L.profit>=0?'+':''}${money(L.profit)}`);}pendingToasts.forEach(toast);pendingToasts=[];}
/* ---------- 0.25: кредит покупателям и вложения свободных денег (13c-finance.js) ---------- */
function finCreditHTML(s){if(!techLv(s,'credit'))return '';const own=finOwn(s),L=s.last||{},cr=L.finCr||0,F=cr*2/3,port=finTotal(s);
  const body=`<p class="small muted" style="margin-top:6px">Покупатель вносит треть цены, остальное платит год. Кто даёт ему деньги?</p>
    <div class="chips" style="margin-top:6px"><button class="chip ${own?'':'on'}" data-act="finPol" data-v="bank">Банки и финансовые дома<small>комиссия ≈ 6% суммы рассрочки${cr?' — '+money(F*FIN_BANK)+' в месяц':''}; ваши деньги свободны</small></button><button class="chip ${own?'on':''}" data-act="finPol" data-v="own">Своя кредитная компания<small>как GMAC (1919): проценты с покупателей ≈ 8% за год — ваш доход; но деньги на рассрочку — ваши${F?`: ≈ ${money(F)} в месяц, вернутся за год`:''}</small></button></div>
    ${own?`<p class="small" style="margin-top:6px">Покупатели должны вашей компании <b class="num">${money(port)}</b> — деньги вернутся за год с процентами. ${L.finInc?`В прошлом месяце: проценты +${money(L.finInc)}, невозвраты −${money(L.finBad||0)}.`:''}</p><p class="small muted" style="margin-top:2px">В кризис (1920–1921, осень 1929-го) не платят втрое-вчетверо чаще. Вернуться к банкам можно в любой месяц: новые рассрочки пойдут через банки, старые долги покупатели вернут как обычно.</p>`
      :`<p class="small muted" style="margin-top:6px">Своя кредитная компания выгодна, когда свободных денег много: вместо комиссии банкам — проценты от покупателей. Нужен запас: портфель рассрочки дорастёт примерно до ${money(F*6.5)}.</p>`}`;
  return `<div class="hr"></div>${fold('finc','Кредит покупателям',body,false,own?`своя кредитная компания · портфель ${money(port)}`:`через банки · комиссия ${money(L.fin||0)} в месяц`)}`;}
function invHTML(s){const I=s.inv||{},bv=bondValue(s),sv=stockVal(s),uv=supValue(s),tot=bv+sv+uv,cash=Math.max(0,s.cash),st=x=>Math.max(1000,Math.round(cash*x/1000)*1000);
  const bRow=c=>{const B=BOND[c],u=(I.b||{})[c]||0,v=u*bondV(c,s),p=bondV(c,s),y=bondC(c,s);
    return `<div class="race-item"><div class="row"><div><h3>${esc(B.n)}</h3><p class="small muted">${esc(B.d)} · купон ${pct(y,1)} годовых · цена ${p>0.001?Math.round(p*100)+'% номинала':'— ничего не стоят'}</p></div><b class="num">${money(v)}</b></div>
      ${c!=='us'&&c!==undefined?`<p class="small muted" style="margin-top:2px">Облигации в местной валюте: если она падает, падает и их цена в долларах.</p>`:''}
      <div class="btns" style="margin-top:6px">${p>0.001?`<button class="btn sm" data-act="invBuy" data-k="${c}" data-n="${st(0.1)}" ${cash<st(0.1)?'disabled':''}>Купить · ${money(st(0.1))}</button><button class="btn sm" data-act="invBuy" data-k="${c}" data-n="${st(0.25)}" ${cash<st(0.25)?'disabled':''}>Купить · ${money(st(0.25))}</button>`:''}${u>0&&p>0?`<button class="btn sm" data-act="invSell" data-k="${c}" data-n="0.5">Продать половину</button><button class="btn sm" data-act="invSell" data-k="${c}" data-n="1">Продать всё</button>`:''}</div></div>`;};
  const sRow=()=>{const open=stocksOpen(s),idx=djia(s);
    return `<div class="race-item"><div class="row"><div><h3>Акции американских компаний</h3><p class="small muted">по индексу Доу-Джонса: сейчас ${Math.round(idx)} · дивиденды ≈ ${pct(divYield(s),1)} годовых</p></div><b class="num">${money(sv)}</b></div>
      ${!open?`<p class="small bad" style="margin-top:4px">Нью-Йоркская биржа закрыта с 31 июля 1914 года: война, все продают. Торги начнутся снова в декабре.</p>`:`<p class="small muted" style="margin-top:2px">Акции растут быстрее облигаций, но падают в паники: 1907 год, война, спад 1920–1921 годов… и осень 1929-го.</p>`}
      <div class="btns" style="margin-top:6px">${open?`<button class="btn sm" data-act="invBuy" data-k="st" data-n="${st(0.1)}" ${cash<st(0.1)?'disabled':''}>Купить · ${money(st(0.1))}</button><button class="btn sm" data-act="invBuy" data-k="st" data-n="${st(0.25)}" ${cash<st(0.25)?'disabled':''}>Купить · ${money(st(0.25))}</button>${I.st>0?`<button class="btn sm" data-act="invSell" data-k="st" data-n="0.5">Продать половину</button><button class="btn sm" data-act="invSell" data-k="st" data-n="1">Продать всё</button>`:''}`:''}</div></div>`;};
  const M=matSpend(s),k=supK(s);
  const uRow=S=>{const u=supOf(s)[S.k],ok=s.y>=S.y,p=u?(u.cover<M*1.6?supPrice(s,S,M*2-u.cover):0):supPrice(s,S),eff=u?S.cut*(S.risk||1)*Math.min(1,u.cover/M):S.cut*(S.risk||1);
    return `<div class="race-item${ok?'':' off'}"><div class="row"><div><h3>${esc(S.n)}</h3><p class="small muted">${ok?`детали дешевле на ${pct(eff,1)}${u&&u.cover<M?' — завод не покрывает весь ваш выпуск: расширьте':''}`:'с '+S.y+' года'}</p></div>${u?`<b class="num">${money(u.val)}</b>`:''}</div>
      <p class="small muted" style="margin-top:2px">${esc(S.d)}</p>
      ${ok?`<div class="btns" style="margin-top:6px">${p?`<button class="btn sm" data-act="supBuy" data-k="${S.k}" ${s.cash<p?'disabled':''}>${u?'Расширить':'Купить'} · ${money(p)}</button>`:''}${u?`<button class="btn sm" data-act="supSell" data-k="${S.k}">Продать · ${money(u.val*0.6)}</button>`:''}</div>`:''}</div>`;};
  const body=`<p class="small muted" style="margin-top:6px">Деньги в кассе не приносят ничего. Их можно вложить: облигации дают купон, акции — дивиденды и рост (и падения), свои поставщики удешевляют детали. Вложения входят в стоимость компании; если касса уйдёт в минус, казначей сам продаст облигации и акции.</p>
    <div class="label" style="margin-top:10px">Облигации · ${money(bv)}</div>${bondKinds(s).map(bRow).join('')}
    <div class="label" style="margin-top:10px">Акции · ${money(sv)}</div>${sRow()}
    <div class="label" style="margin-top:10px">Свои поставщики · ${money(uv)}${k<0.999?` · детали дешевле на ${pct(1-k,1)}`:''}</div>${SUPPLY.map(uRow).join('')}`;
  return `<div class="hr"></div>${fold('inv','Вложения свободных денег',body,false,tot>0?`вложено ${money(tot)}${s.last&&s.last.invInc?` · доход ${money(s.last.invInc)} в месяц`:''}`:'облигации, акции, свои поставщики')}`;}
